language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
services:
  - mongodb
  - rabbitmq
script: coverage run --omit=lib/daemon/* --source=. tests/unittests.py
after_success: coveralls
