# -*- coding: utf-8 -*-
from collections import OrderedDict



# TODO(rca): remove the unnecessary tests; it is bloody confusing what is what in here

GENERAL = OrderedDict([(u'@origin', u'AAS'),
             (u'@type', u'general'),
             (u'@primary', u'True'),
             (u'@alternate_journal', u'False'),
             (u'creation_time', u'2012-08-06T19:12:47'),
             (u'modification_time', u'2012-08-06T19:12:47'),
             (u'bibcode', u'2010AAS...21542816H'),
             (u'dates',
              OrderedDict([(u'date',
                            OrderedDict([(u'@type', u'date-published'),
                                         ('#text', u'2010-01-00')]))])),
             (u'title',
              u'Characteristics Of Hydrocarbon Emission From Herbig Ae/be Stars'),
             (u'abstract',
              u'We present analysis of polycyclic aromatic hydrocarbon (PAH) emission in mid-infrared spectra of a large sample of Herbig Ae and Be (HAeBe) stars. The spectra were obtained with the Infrared Spectrograph on the Spitzer Space Telescope. In a previous study of 18 HAeBe stars we found: evidence that the PAH ionization fraction in the circumstellar material around HAeBe stars is related to the structure of the PAH molecules; that the center wavelengths of the PAH emission features change systematically with stellar effective temperature changes; and that HAeBe stars have may have unique mid-infrared spectral characteristics that distinguish them from other strong PAH emission sources. We also found no simple correlation between the integrated intensity of PAH emission from HAeBe stars and the geometry of their proto-planetary disks. We now have expanded the sample to include 50 stars using archival data from the Spitzer database. We present a similar analysis applied to the larger sample.'),
             (u'author',
              [OrderedDict([(u'@nr', u'1'),
                            (u'name',
                             OrderedDict([(u'western', u'Hyatt, Jordan'),
                                          (u'normalized', u'Hyatt, J')])),
                            (u'affiliations',
                             OrderedDict([(u'affiliation',
                                           u'Ithaca College')])),
                            (u'type', u'regular')]),
               OrderedDict([(u'@nr', u'2'),
                            (u'name',
                             OrderedDict([(u'western', u'Keller, L. D.'),
                                          (u'normalized', u'Keller, L')])),
                            (u'affiliations',
                             OrderedDict([(u'affiliation',
                                           u'Ithaca College')])),
                            (u'type', u'regular')]),
               OrderedDict([(u'@nr', u'3'),
                            (u'name',
                             OrderedDict([(u'western', u'Sloan, G. C.'),
                                          (u'normalized', u'Sloan, G')])),
                            (u'affiliations',
                             OrderedDict([(u'affiliation',
                                           u'Cornell University')])),
                            (u'type', u'regular')]),
               OrderedDict([(u'@nr', u'4'),
                            (u'name',
                             OrderedDict([(u'western', u'Geidel, K. L.'),
                                          (u'normalized', u'Geidel, K')])),
                            (u'affiliations',
                             OrderedDict([(u'affiliation',
                                           u'Ithaca College')])),
                            (u'type', u'regular')])]),
             (u'ADSaffiliation',
              u'AA(Ithaca College), AB(Ithaca College), AC(Cornell University), AD(Ithaca College)'),
             (u'journal',
              u'American Astronomical Society, AAS Meeting #215, #428.16; <ALTJOURNAL>Bulletin of the American Astronomical Society, Vol. 42, p.347</ALTJOURNAL>'),
             (u'canonical_journal',
              u'American Astronomical Society Meeting Abstracts #215'),
             (u'electronic_id', u'428.16'),
             (u'publication_year', u'2010'),
             (u'volume', u'215'),
             (u'series', '123')])

PROPERTIES = OrderedDict([(u'@origin', u'ADS metadata'),
             (u'series', None),
             (u'vizier_tables',
              OrderedDict([(u'vizier_table',
                            [u'Galaxies', u'HII regions', u'Optical'])])),
             (u'@type', u'properties'),
             (u'@primary', u'False'),
             (u'@alternate_journal', u'False'),
             (u'JSON_timestamp',
              u'{"abs":[{"p":"/proj/ads/abstracts/ast/text/A85/A85-29431.abs","primary":1,"t":"1386214979"},{"p":"/proj/ads/abstracts/ast/text/J85/J85-29431.abs","t":"1321421644"},{"p":"/proj/ads/abstracts/ast/text/S85/S85-29431.abs","t":"1347305751"}],"full":[{"p":"/proj/ads/fulltext/extracted/19/85/A&/A,/,,/14/2,/,,/,1/K//meta.json","t":1395490755},{"p":"/proj/ads/fulltext/extracted/19/85/A&/A,/,,/14/2,/,,/,1/K//fulltext.txt","t":1363068221}],"links":{"associated":[{"t":"Part  1","u":"1983IAUS..100...99V"},{"t":"Part  2","u":"1984A&A...133..127K"},{"t":"Part  3","u":"1985A&A...142....1K"},{"t":"Part  4","u":"1985A&A...144..202K"},{"t":"Part  5","u":"1988A&A...191..201V"},{"t":"Part  6","u":"1988A&A...199...41V"},{"t":"Part  7","u":"1988A&A...204...39V"},{"t":"Part  8","u":"1989A&A...218...49V"},{"t":"Part  9","u":"1989A&A...225..317V"},{"t":"Part 11","u":"1991A&A...243...71V"},{"t":"Part 10","u":"1993A&A...269...15V"}],"ned":[{"c":"1","u":"http://$NED$/cgi-bin/nph-objsearch?search_type=Search&refcode=1985A%26A...142....1K"}]},"prop":["article","refereed"],"refs":[{"p":"/proj/ads/references/resolved/A&A/0142/1985A&A...142....1K.ref.ocr.txt.result","t":1374509778},{"p":"/proj/ads/references/resolved/ISI/A&A/A&A0142.isi.pairs.result","t":1302279738}]}'),
             (u'databases', OrderedDict([(u'database', u'AST')])),
             (u'data_sources', OrderedDict([(u'data_source', u'NED')])),
             (u'pubtype', u'article'),
             (u'refereed', u'1'),
             (u'openaccess', u'1'),
             (u'pub_openaccess', u'0'),
             (u'private', u'0'),
             (u'ocrabstract', u'0'),
             (u'ads_openaccess', u'1'),
             (u'eprint_openaccess', u'0'),
             (u'preprint', None),
             (u'nonarticle', u'0'),
             (u'associates',
              OrderedDict([(u'associate',
                            [OrderedDict([(u'@comment', u'Part  1'),
                                          ('#text', u'1983IAUS..100...99V')]),
                             OrderedDict([(u'@comment', u'Part  2'),
                                          ('#text', u'1984A&A...133..127K')]),
                             OrderedDict([(u'@comment', u'Part  3'),
                                          ('#text', u'1985A&A...142....1K')]),
                             OrderedDict([(u'@comment', u'Part  4'),
                                          ('#text', u'1985A&A...144..202K')]),
                             OrderedDict([(u'@comment', u'Part  5'),
                                          ('#text', u'1988A&A...191..201V')]),
                             OrderedDict([(u'@comment', u'Part  6'),
                                          ('#text', u'1988A&A...199...41V')]),
                             OrderedDict([(u'@comment', u'Part  7'),
                                          ('#text', u'1988A&A...204...39V')]),
                             OrderedDict([(u'@comment', u'Part  8'),
                                          ('#text', u'1989A&A...218...49V')]),
                             OrderedDict([(u'@comment', u'Part  9'),
                                          ('#text', u'1989A&A...225..317V')]),
                             OrderedDict([(u'@comment', u'Part 11'),
                                          ('#text', u'1991A&A...243...71V')]),
                             OrderedDict([(u'@comment', u'Part 10'),
                                          ('#text',
                                           u'1993A&A...269...15V')])])]))])
REFERENCES = OrderedDict([(u'@origin', u'ISI'),
             (u'@source', u'A&A0142.isi.pairs'),
             (u'@type', u'references'),
             (u'@primary', u'False'),
             (u'@alternate_journal', u'False'),
             (u'creation_time', u'2011-04-08T16:22:18'),
             (u'modification_time', u'2011-04-08T16:22:18'),
             (u'reference',
              [OrderedDict([(u'@origin', u'ISI'),
                            (u'@bibcode', u'1981A&A....98..251B'),
                            (u'@score', u'1'),
                            (u'@arxid', u''),
                            (u'@doi', u''),
                            ('#text', u'1981A&A....98..251B')]),
               OrderedDict([(u'@origin', u'ISI'),
                            (u'@bibcode', u'1981ApJ...246..666T'),
                            (u'@score', u'1'),
                            (u'@arxid', u''),
                            (u'@doi', u''),
                            ('#text', u'1981ApJ...246..666T')]),
               OrderedDict([(u'@origin', u'ISI'),
                            (u'@bibcode', u'1981ApJ...246L.105H'),
                            (u'@score', u'1'),
                            (u'@arxid', u''),
                            (u'@doi', u''),
                            ('#text', u'1981ApJ...246L.105H')]),
               OrderedDict([(u'@origin', u'ISI'),
                            (u'@bibcode', u'1981MNRAS.196..747H'),
                            (u'@score', u'1'),
                            (u'@arxid', u''),
                            (u'@doi', u''),
                            ('#text', u'1981MNRAS.196..747H')]),
               OrderedDict([(u'@origin', u'ISI'),
                            (u'@bibcode', u'1982A&A...114..400H'),
                            (u'@score', u'1'),
                            (u'@arxid', u''),
                            (u'@doi', u''),
                            ('#text', u'1982A&A...114..400H')]),
               OrderedDict([(u'@origin', u'ISI'),
                            (u'@bibcode', u'1982ApJ...252..125T'),
                            (u'@score', u'1'),
                            (u'@arxid', u''),
                            (u'@doi', u''),
                            ('#text', u'1982ApJ...252..125T')]),
               OrderedDict([(u'@origin', u'ISI'),
                            (u'@bibcode', u'1982ApJ...256..460K'),
                            (u'@score', u'1'),
                            (u'@arxid', u''),
                            (u'@doi', u''),
                            ('#text', u'1982ApJ...256..460K')]),
               OrderedDict([(u'@origin', u'ISI'),
                            (u'@bibcode', u'1982ApJ...258...64A'),
                            (u'@score', u'1'),
                            (u'@arxid', u''),
                            (u'@doi', u''),
                            ('#text', u'1982ApJ...258...64A')]),
               OrderedDict([(u'@origin', u'ISI'),
                            (u'@bibcode', u'1983MNRAS.202...37S'),
                            (u'@score', u'1'),
                            (u'@arxid', u''),
                            (u'@doi', u''),
                            ('#text', u'1983MNRAS.202...37S')]),
               OrderedDict([(u'@origin', u'ISI'),
                            (u'@bibcode', u'1983MNRAS.202.1001B'),
                            (u'@score', u'1'),
                            (u'@arxid', u''),
                            (u'@doi', u''),
                            ('#text', u'1983MNRAS.202.1001B')]),
               OrderedDict([(u'@origin', u'ISI'),
                            (u'@bibcode', u'1984A&A...141..309B'),
                            (u'@score', u'1'),
                            (u'@arxid', u''),
                            (u'@doi', u''),
                            ('#text', u'1984A&A...141..309B')]),
               OrderedDict([(u'@origin', u'ISI'),
                            (u'@bibcode', u'1984MNRAS.208..111S'),
                            (u'@score', u'1'),
                            (u'@arxid', u''),
                            (u'@doi', u''),
                            ('#text', u'1984MNRAS.208..111S')])])]) 
RELATIONS = OrderedDict([(u'@origin', u'ADS metadata'),
             (u'@type', u'relations'),
             (u'@primary', u'False'),
             (u'@alternate_journal', u'False'),
             (u'alternates', None),
             (u'links',
              OrderedDict([(u'link',
                            [OrderedDict([(u'@url',
                                           u'http://$NED$/cgi-bin/nph-objsearch?search_type=Search&refcode=1985A%26A...142....1K'),
                                          (u'@count', u'1'),
                                          (u'@type', u'ned')]),
                             OrderedDict([(u'@url',
                                           u'http://adsabs.harvard.edu/abs/1985A%26A...142....1K'),
                                          (u'@type', u'ADSlink')])])]))])
 
GENERAL_ENFORCED = {'abstracts': [{'lang': u'en',
   'origin': u'AAS',
   'text': u'We present analysis of polycyclic aromatic hydrocarbon (PAH) emission in mid-infrared spectra of a large sample of Herbig Ae and Be (HAeBe) stars. The spectra were obtained with the Infrared Spectrograph on the Spitzer Space Telescope. In a previous study of 18 HAeBe stars we found: evidence that the PAH ionization fraction in the circumstellar material around HAeBe stars is related to the structure of the PAH molecules; that the center wavelengths of the PAH emission features change systematically with stellar effective temperature changes; and that HAeBe stars have may have unique mid-infrared spectral characteristics that distinguish them from other strong PAH emission sources. We also found no simple correlation between the integrated intensity of PAH emission from HAeBe stars and the geometry of their proto-planetary disks. We now have expanded the sample to include 50 stars using archival data from the Spitzer database. We present a similar analysis applied to the larger sample.'}],
 'arxivcategories': [],
 'authors': [{'affiliations': [u'Ithaca College'],
   'emails': [],
   'name': {'native': None,
    'normalized': u'Hyatt, J',
    'western': u'Hyatt, Jordan'},
   'number': u'1',
   'orcid': None,
   'type': u'regular'},
  {'affiliations': [u'Ithaca College'],
   'emails': [],
   'name': {'native': None,
    'normalized': u'Keller, L',
    'western': u'Keller, L. D.'},
   'number': u'2',
   'orcid': None,
   'type': u'regular'},
  {'affiliations': [u'Cornell University'],
   'emails': [],
   'name': {'native': None,
    'normalized': u'Sloan, G',
    'western': u'Sloan, G. C.'},
   'number': u'3',
   'orcid': None,
   'type': u'regular'},
  {'affiliations': [u'Ithaca College'],
   'emails': [],
   'name': {'native': None,
    'normalized': u'Geidel, K',
    'western': u'Geidel, K. L.'},
   'number': u'4',
   'orcid': None,
   'type': u'regular'}],
 'comment': [],
 'conf_metadata': {'content': None, 'origin': u'AAS'},
 'copyright': [],
 'doi': [],
 'isbns': [],
 'issns': [],
 'keywords': [],
 'language': '',
 'publication': {'altbibcode': u'2010AAS...21542816H',
  'dates': [{'content': u'2010-01-00', 'type': u'date-published'},
   {'content': u'2010', 'type': 'publication_year'}],
  'electronic_id': u'428.16',
  'issue': None,
  'name': {'canonical': u'American Astronomical Society Meeting Abstracts #215',
   'raw': u'American Astronomical Society, AAS Meeting #215, #428.16; <ALTJOURNAL>Bulletin of the American Astronomical Society, Vol. 42, p.347</ALTJOURNAL>'},
  'origin': u'AAS',
  'page': None,
  'page_count': None,
  'page_last': None,
  'page_range': None,
  'series': '123',
  'volume': u'215'},
 'pubnote': [],
 'tempdata': {'alternate_journal': False,
  'modtime': u'2012-08-06T19:12:47',
  'origin': u'AAS',
  'primary': True,
  'type': u'general'},
 'titles': [{'lang': u'en',
   'text': u'Characteristics Of Hydrocarbon Emission From Herbig Ae/be Stars'}]}

PROPERTIES_ENFORCED = {'ads_openaccess': True,
 'associates': [{'comment': u'Part  1',
   'content': u'1983IAUS..100...99V',
   'origin': u'ADS metadata'},
  {'comment': u'Part  2',
   'content': u'1984A&A...133..127K',
   'origin': u'ADS metadata'},
  {'comment': u'Part  3',
   'content': u'1985A&A...142....1K',
   'origin': u'ADS metadata'},
  {'comment': u'Part  4',
   'content': u'1985A&A...144..202K',
   'origin': u'ADS metadata'},
  {'comment': u'Part  5',
   'content': u'1988A&A...191..201V',
   'origin': u'ADS metadata'},
  {'comment': u'Part  6',
   'content': u'1988A&A...199...41V',
   'origin': u'ADS metadata'},
  {'comment': u'Part  7',
   'content': u'1988A&A...204...39V',
   'origin': u'ADS metadata'},
  {'comment': u'Part  8',
   'content': u'1989A&A...218...49V',
   'origin': u'ADS metadata'},
  {'comment': u'Part  9',
   'content': u'1989A&A...225..317V',
   'origin': u'ADS metadata'},
  {'comment': u'Part 11',
   'content': u'1991A&A...243...71V',
   'origin': u'ADS metadata'},
  {'comment': u'Part 10',
   'content': u'1993A&A...269...15V',
   'origin': u'ADS metadata'}],
 'bibgroups': [],
 'data_sources': [{'content': u'NED', 'origin': u'ADS metadata'}],
 'databases': [{'content': u'AST', 'origin': u'ADS metadata'}],
 'doctype': {'content': u'article', 'origin': u'ADS metadata'},
 'eprint_openaccess': False,
 'ocrabstract': False,
 'openaccess': True,
 'private': False,
 'pub_openaccess': False,
 'refereed': True,
 'tempdata': {'alternate_journal': False,
  'modtime': None,
  'origin': u'ADS metadata',
  'primary': False,
  'type': u'properties'},
 'vizier_tables': [{'content': u'Galaxies', 'origin': u'ADS metadata'},
  {'content': u'HII regions', 'origin': u'ADS metadata'},
  {'content': u'Optical', 'origin': u'ADS metadata'}]}

REFERENCES_ENFORCED = {'references': [{'arxid': u'',
   'bibcode': u'1981A&A....98..251B',
   'content': u'1981A&A....98..251B',
   'doi': u'',
   'extension': None,
   'origin': u'ISI',
   'score': u'1'},
  {'arxid': u'',
   'bibcode': u'1981ApJ...246..666T',
   'content': u'1981ApJ...246..666T',
   'doi': u'',
   'extension': None,
   'origin': u'ISI',
   'score': u'1'},
  {'arxid': u'',
   'bibcode': u'1981ApJ...246L.105H',
   'content': u'1981ApJ...246L.105H',
   'doi': u'',
   'extension': None,
   'origin': u'ISI',
   'score': u'1'},
  {'arxid': u'',
   'bibcode': u'1981MNRAS.196..747H',
   'content': u'1981MNRAS.196..747H',
   'doi': u'',
   'extension': None,
   'origin': u'ISI',
   'score': u'1'},
  {'arxid': u'',
   'bibcode': u'1982A&A...114..400H',
   'content': u'1982A&A...114..400H',
   'doi': u'',
   'extension': None,
   'origin': u'ISI',
   'score': u'1'},
  {'arxid': u'',
   'bibcode': u'1982ApJ...252..125T',
   'content': u'1982ApJ...252..125T',
   'doi': u'',
   'extension': None,
   'origin': u'ISI',
   'score': u'1'},
  {'arxid': u'',
   'bibcode': u'1982ApJ...256..460K',
   'content': u'1982ApJ...256..460K',
   'doi': u'',
   'extension': None,
   'origin': u'ISI',
   'score': u'1'},
  {'arxid': u'',
   'bibcode': u'1982ApJ...258...64A',
   'content': u'1982ApJ...258...64A',
   'doi': u'',
   'extension': None,
   'origin': u'ISI',
   'score': u'1'},
  {'arxid': u'',
   'bibcode': u'1983MNRAS.202...37S',
   'content': u'1983MNRAS.202...37S',
   'doi': u'',
   'extension': None,
   'origin': u'ISI',
   'score': u'1'},
  {'arxid': u'',
   'bibcode': u'1983MNRAS.202.1001B',
   'content': u'1983MNRAS.202.1001B',
   'doi': u'',
   'extension': None,
   'origin': u'ISI',
   'score': u'1'},
  {'arxid': u'',
   'bibcode': u'1984A&A...141..309B',
   'content': u'1984A&A...141..309B',
   'doi': u'',
   'extension': None,
   'origin': u'ISI',
   'score': u'1'},
  {'arxid': u'',
   'bibcode': u'1984MNRAS.208..111S',
   'content': u'1984MNRAS.208..111S',
   'doi': u'',
   'extension': None,
   'origin': u'ISI',
   'score': u'1'}],
 'tempdata': {'alternate_journal': False,
  'modtime': u'2011-04-08T16:22:18',
  'origin': u'ISI',
  'primary': False,
  'type': u'references'}}



RELATIONS_ENFORCED = {'alternates': [],
 'identifiers': [],
 'links': [{'access': None,
   'count': u'1',
   'origin': None,
   'title': None,
   'type': u'ned',
   'url': u'http://$NED$/cgi-bin/nph-objsearch?search_type=Search&refcode=1985A%26A...142....1K'}],
 'preprints': [],
 'tempdata': {'alternate_journal': False,
  'modtime': None,
  'origin': u'ADS metadata',
  'primary': False,
  'type': u'relations'}}

# expected output from processing
MERGEDRECS = {}
MERGEDRECS[u'2015ApJ...815..133S'] = {'abstract': u'In order to examine their relation to the host galaxy, the extraplanar dusts of six nearby galaxies are modeled, employing a three-dimensional Monte Carlo radiative transfer code. The targets are from the highly inclined galaxies that show dust-scattered ultraviolet halos, and the archival Galaxy Evolution Explorer FUV band images were fitted with the model. The observed images are generally well-reproduced by two dust layers and one light source layer, whose vertical and radial distributions have exponential profiles. We obtained several important physical parameters, such as star formation rate (SFR<SUB>UV</SUB>), face-on optical depth, and scale-heights. Three galaxies (NGC 891, NGC 3628, and UGC 11794) show clear evidence for the existence of an extraplanar dust layer. However, it is found that the remaining three targets (IC 5249, NGC 24, and NGC 4173) do not necessarily need a thick dust disk to model the ultraviolet (UV) halo, because its contribution is too small and the UV halo may be caused by the wing part of the GALEX point spread function. This indicates that the galaxy samples reported to have UV halos may be contaminated by galaxies with negligible extraplanar (halo) dust. The galaxies showing evidence of an extraplanar dust layer fall within a narrow range on the scatter plots between physical parameters such as SFR<SUB>UV</SUB> and extraplanar dust mass. Several mechanisms that could possibly produce the extraplanar dust are discussed. We also found a hint that the extraplanar dust scale-height might not be much different from the polycyclic aromatic hydrocarbon emission characteristic height.',
         'ack': u'J.H.S. is grateful to Yujin Yang, Dennis Zaritsky, and Ann Zabludoff for their valuable comments and discussion of the results.',
         'aff': [u'Korea Astronomy and Space Science Institute, 776 Daeduk-daero, Yuseong-gu, Daejeon, 305-348, Korea',
          u'Korea Astronomy and Space Science Institute, 776 Daeduk-daero, Yuseong-gu, Daejeon, 305-348, Korea; Astronomy and Space Science Major, Korea University of Science and Technology, 217 Gajeong-ro, Yuseong-gu, Daejeon, 305-350, Korea; Department of Astrophysical Sciences, Princeton University, Princeton NJ 08544, USA'],
         'alternate_bibcode': [u'2015arXiv151103789S'],
         'arxiv_class': [u'Astrophysics - Astrophysics of Galaxies'],
         'author': [u'Shinn, Jong-Ho', u'Seon, Kwang-Il'],
         'author_count': 2,
         'author_facet': [u'Shinn, J', u'Seon, K'],
         'author_facet_hier': [u'0/Shinn, J',
          u'1/Shinn, J/Shinn, Jong-Ho',
          u'0/Seon, K',
          u'1/Seon, K/Seon, Kwang-Il'],
         'author_norm': [u'Shinn, J', u'Seon, K'],
         'bibcode': u'2015ApJ...815..133S',
         'bibstem': [u'ApJ', u'ApJ...815'],
         'bibstem_facet': u'ApJ',
         'database': [u'astronomy'],
         'date': u'2015-12-01T00:00:00.000000Z',
         'doctype': u'article',
         'doctype_facet_hier': [u'0/Article', u'1/Article/Journal Article'],
         'doi': [u'10.1088/0004-637X/815/2/133'],
         'eid': u'133',
         'email': [u'jhshinn@kasi.re.kr', u'-'],
         'entry_date': '2003-01-01T00:00:00.000000Z',
         'first_author': u'Shinn, Jong-Ho',
         'first_author_facet_hier': [u'0/Shinn, J', u'1/Shinn, J/Shinn, Jong-Ho'],
         'first_author_norm': u'Shinn, J',
         'identifier': [u'1511.03789',
          u'10.1088/0004-637X/815/2/133',
          u'2015ApJ...815..133S',
          u'2015arXiv151103789S'],
         'issue': u'2',
         'keyword': [u'dust',
          u'extinction',
          u'galaxies: halos',
          u'galaxies: ISM',
          u'galaxies: spiral',
          u'galaxies: star formation',
          u'radiative transfer',
          u'Astrophysics - Astrophysics of Galaxies'],
         'keyword_facet': [u'dust',
          u'ism dust extinction',
          u'galaxies halos',
          u'galaxies intergalactic medium',
          u'galaxies spiral',
          u'galaxies star clusters',
          u'radiative transfer'],
         'keyword_norm': [u'dust',
          u'ism dust extinction',
          u'galaxies halos',
          u'galaxies intergalactic medium',
          u'galaxies spiral',
          u'galaxies star clusters',
          u'radiative transfer',
          u'-'],
         'keyword_schema': [u'Astronomy',
          u'Astronomy',
          u'Astronomy',
          u'Astronomy',
          u'Astronomy',
          u'Astronomy',
          u'Astronomy',
          u'arXiv'],
         'links_data': [u'{"access": "", "instances": "7", "title": "", "type": "simbad", "url": "http://$SIMBAD$/simbo.pl?bibcode=2015ApJ...815..133S"}',
          u'{"access": "open", "instances": "", "title": "", "type": "pdf", "url": "http://stacks.iop.org/0004-637X/815/133/pdf"}',
          u'{"access": "", "instances": "6", "title": "", "type": "ned", "url": "http://ned.ipac.caltech.edu/cgi-bin/nph-objsearch?search_type=Search&refcode=2015ApJ...815..133S"}',
          u'{"access": "open", "instances": "", "title": "", "type": "preprint", "url": "http://arxiv.org/abs/1511.03789"}',
          u'{"access": "open", "instances": "", "title": "", "type": "electr", "url": "http://dx.doi.org/10.1088%2F0004-637X%2F815%2F2%2F133"}'],
         'orcid_pub': [u'0000-0001-7967-6473', u'0000-0001-9561-8134'],
         'page': [u'133'],
         'page_count': 14,
         'pub': u'The Astrophysical Journal',
         'pub_raw': u'The Astrophysical Journal, Volume 815, Issue 2, article id. 133, <NUMPAGES>14</NUMPAGES> pp. (2015).',
         'pubdate': u'2015-12-00',
         'pubnote': [u'33 pages, 7 figures, 5 tables, ApJ in press; doi:10.1088/0004-637X/815/2/133'],
         'title': [u'Ultraviolet Radiative Transfer Modeling of Nearby Galaxies with Extraplanar Dusts'],
         'volume': u'815',
         'series': '123',
         'year': u'2015'}
