# -*- coding: utf-8 -*-
from collections import OrderedDict
import os

GENERAL = OrderedDict([(u'@origin', u'AAS'),
             (u'@type', u'general'),
             (u'@primary', u'True'),
             (u'@alternate_journal', u'False'),
             (u'creation_time', u'2012-08-06T19:12:47'),
             (u'modification_time', u'2012-08-06T19:12:47'),
             (u'bibcode', u'2010AAS...21542816H'),
             (u'dates',
              OrderedDict([(u'date',
                            OrderedDict([(u'@type', u'date-published'),
                                         ('#text', u'2010-01-00')]))])),
             (u'title',
              u'Characteristics Of Hydrocarbon Emission From Herbig Ae/be Stars'),
             (u'abstract',
              u'We present analysis of polycyclic aromatic hydrocarbon (PAH) emission in mid-infrared spectra of a large sample of Herbig Ae and Be (HAeBe) stars. The spectra were obtained with the Infrared Spectrograph on the Spitzer Space Telescope. In a previous study of 18 HAeBe stars we found: evidence that the PAH ionization fraction in the circumstellar material around HAeBe stars is related to the structure of the PAH molecules; that the center wavelengths of the PAH emission features change systematically with stellar effective temperature changes; and that HAeBe stars have may have unique mid-infrared spectral characteristics that distinguish them from other strong PAH emission sources. We also found no simple correlation between the integrated intensity of PAH emission from HAeBe stars and the geometry of their proto-planetary disks. We now have expanded the sample to include 50 stars using archival data from the Spitzer database. We present a similar analysis applied to the larger sample.'),
             (u'author',
              [OrderedDict([(u'@nr', u'1'),
                            (u'name',
                             OrderedDict([(u'western', u'Hyatt, Jordan'),
                                          (u'normalized', u'Hyatt, J')])),
                            (u'affiliations',
                             OrderedDict([(u'affiliation',
                                           u'Ithaca College')])),
                            (u'type', u'regular')]),
               OrderedDict([(u'@nr', u'2'),
                            (u'name',
                             OrderedDict([(u'western', u'Keller, L. D.'),
                                          (u'normalized', u'Keller, L')])),
                            (u'affiliations',
                             OrderedDict([(u'affiliation',
                                           u'Ithaca College')])),
                            (u'type', u'regular')]),
               OrderedDict([(u'@nr', u'3'),
                            (u'name',
                             OrderedDict([(u'western', u'Sloan, G. C.'),
                                          (u'normalized', u'Sloan, G')])),
                            (u'affiliations',
                             OrderedDict([(u'affiliation',
                                           u'Cornell University')])),
                            (u'type', u'regular')]),
               OrderedDict([(u'@nr', u'4'),
                            (u'name',
                             OrderedDict([(u'western', u'Geidel, K. L.'),
                                          (u'normalized', u'Geidel, K')])),
                            (u'affiliations',
                             OrderedDict([(u'affiliation',
                                           u'Ithaca College')])),
                            (u'type', u'regular')])]),
             (u'ADSaffiliation',
              u'AA(Ithaca College), AB(Ithaca College), AC(Cornell University), AD(Ithaca College)'),
             (u'journal',
              u'American Astronomical Society, AAS Meeting #215, #428.16; <ALTJOURNAL>Bulletin of the American Astronomical Society, Vol. 42, p.347</ALTJOURNAL>'),
             (u'canonical_journal',
              u'American Astronomical Society Meeting Abstracts #215'),
             (u'electronic_id', u'428.16'),
             (u'publication_year', u'2010'),
             (u'volume', u'215')])

PROPERTIES = OrderedDict([(u'@origin', u'ADS metadata'),
             (u'vizier_tables',
              OrderedDict([(u'vizier_table',
                            [u'Galaxies', u'HII regions', u'Optical'])])),
             (u'@type', u'properties'),
             (u'@primary', u'False'),
             (u'@alternate_journal', u'False'),
             (u'JSON_timestamp',
              u'{"abs":[{"p":"/proj/ads/abstracts/ast/text/A85/A85-29431.abs","primary":1,"t":"1386214979"},{"p":"/proj/ads/abstracts/ast/text/J85/J85-29431.abs","t":"1321421644"},{"p":"/proj/ads/abstracts/ast/text/S85/S85-29431.abs","t":"1347305751"}],"full":[{"p":"/proj/ads/fulltext/extracted/19/85/A&/A,/,,/14/2,/,,/,1/K//meta.json","t":1395490755},{"p":"/proj/ads/fulltext/extracted/19/85/A&/A,/,,/14/2,/,,/,1/K//fulltext.txt","t":1363068221}],"links":{"associated":[{"t":"Part  1","u":"1983IAUS..100...99V"},{"t":"Part  2","u":"1984A&A...133..127K"},{"t":"Part  3","u":"1985A&A...142....1K"},{"t":"Part  4","u":"1985A&A...144..202K"},{"t":"Part  5","u":"1988A&A...191..201V"},{"t":"Part  6","u":"1988A&A...199...41V"},{"t":"Part  7","u":"1988A&A...204...39V"},{"t":"Part  8","u":"1989A&A...218...49V"},{"t":"Part  9","u":"1989A&A...225..317V"},{"t":"Part 11","u":"1991A&A...243...71V"},{"t":"Part 10","u":"1993A&A...269...15V"}],"ned":[{"c":"1","u":"http://$NED$/cgi-bin/nph-objsearch?search_type=Search&refcode=1985A%26A...142....1K"}]},"prop":["article","refereed"],"refs":[{"p":"/proj/ads/references/resolved/A&A/0142/1985A&A...142....1K.ref.ocr.txt.result","t":1374509778},{"p":"/proj/ads/references/resolved/ISI/A&A/A&A0142.isi.pairs.result","t":1302279738}]}'),
             (u'databases', OrderedDict([(u'database', u'AST')])),
             (u'data_sources', OrderedDict([(u'data_source', u'NED')])),
             (u'pubtype', u'article'),
             (u'refereed', u'1'),
             (u'openaccess', u'1'),
             (u'pub_openaccess', u'0'),
             (u'private', u'0'),
             (u'ocrabstract', u'0'),
             (u'ads_openaccess', u'1'),
             (u'eprint_openaccess', u'0'),
             (u'preprint', None),
             (u'nonarticle', u'0'),
             (u'associates',
              OrderedDict([(u'associate',
                            [OrderedDict([(u'@comment', u'Part  1'),
                                          ('#text', u'1983IAUS..100...99V')]),
                             OrderedDict([(u'@comment', u'Part  2'),
                                          ('#text', u'1984A&A...133..127K')]),
                             OrderedDict([(u'@comment', u'Part  3'),
                                          ('#text', u'1985A&A...142....1K')]),
                             OrderedDict([(u'@comment', u'Part  4'),
                                          ('#text', u'1985A&A...144..202K')]),
                             OrderedDict([(u'@comment', u'Part  5'),
                                          ('#text', u'1988A&A...191..201V')]),
                             OrderedDict([(u'@comment', u'Part  6'),
                                          ('#text', u'1988A&A...199...41V')]),
                             OrderedDict([(u'@comment', u'Part  7'),
                                          ('#text', u'1988A&A...204...39V')]),
                             OrderedDict([(u'@comment', u'Part  8'),
                                          ('#text', u'1989A&A...218...49V')]),
                             OrderedDict([(u'@comment', u'Part  9'),
                                          ('#text', u'1989A&A...225..317V')]),
                             OrderedDict([(u'@comment', u'Part 11'),
                                          ('#text', u'1991A&A...243...71V')]),
                             OrderedDict([(u'@comment', u'Part 10'),
                                          ('#text',
                                           u'1993A&A...269...15V')])])]))])
REFERENCES = OrderedDict([(u'@origin', u'ISI'),
             (u'@source', u'A&A0142.isi.pairs'),
             (u'@type', u'references'),
             (u'@primary', u'False'),
             (u'@alternate_journal', u'False'),
             (u'creation_time', u'2011-04-08T16:22:18'),
             (u'modification_time', u'2011-04-08T16:22:18'),
             (u'reference',
              [OrderedDict([(u'@origin', u'ISI'),
                            (u'@bibcode', u'1981A&A....98..251B'),
                            (u'@score', u'1'),
                            (u'@arxid', u''),
                            (u'@doi', u''),
                            ('#text', u'1981A&A....98..251B')]),
               OrderedDict([(u'@origin', u'ISI'),
                            (u'@bibcode', u'1981ApJ...246..666T'),
                            (u'@score', u'1'),
                            (u'@arxid', u''),
                            (u'@doi', u''),
                            ('#text', u'1981ApJ...246..666T')]),
               OrderedDict([(u'@origin', u'ISI'),
                            (u'@bibcode', u'1981ApJ...246L.105H'),
                            (u'@score', u'1'),
                            (u'@arxid', u''),
                            (u'@doi', u''),
                            ('#text', u'1981ApJ...246L.105H')]),
               OrderedDict([(u'@origin', u'ISI'),
                            (u'@bibcode', u'1981MNRAS.196..747H'),
                            (u'@score', u'1'),
                            (u'@arxid', u''),
                            (u'@doi', u''),
                            ('#text', u'1981MNRAS.196..747H')]),
               OrderedDict([(u'@origin', u'ISI'),
                            (u'@bibcode', u'1982A&A...114..400H'),
                            (u'@score', u'1'),
                            (u'@arxid', u''),
                            (u'@doi', u''),
                            ('#text', u'1982A&A...114..400H')]),
               OrderedDict([(u'@origin', u'ISI'),
                            (u'@bibcode', u'1982ApJ...252..125T'),
                            (u'@score', u'1'),
                            (u'@arxid', u''),
                            (u'@doi', u''),
                            ('#text', u'1982ApJ...252..125T')]),
               OrderedDict([(u'@origin', u'ISI'),
                            (u'@bibcode', u'1982ApJ...256..460K'),
                            (u'@score', u'1'),
                            (u'@arxid', u''),
                            (u'@doi', u''),
                            ('#text', u'1982ApJ...256..460K')]),
               OrderedDict([(u'@origin', u'ISI'),
                            (u'@bibcode', u'1982ApJ...258...64A'),
                            (u'@score', u'1'),
                            (u'@arxid', u''),
                            (u'@doi', u''),
                            ('#text', u'1982ApJ...258...64A')]),
               OrderedDict([(u'@origin', u'ISI'),
                            (u'@bibcode', u'1983MNRAS.202...37S'),
                            (u'@score', u'1'),
                            (u'@arxid', u''),
                            (u'@doi', u''),
                            ('#text', u'1983MNRAS.202...37S')]),
               OrderedDict([(u'@origin', u'ISI'),
                            (u'@bibcode', u'1983MNRAS.202.1001B'),
                            (u'@score', u'1'),
                            (u'@arxid', u''),
                            (u'@doi', u''),
                            ('#text', u'1983MNRAS.202.1001B')]),
               OrderedDict([(u'@origin', u'ISI'),
                            (u'@bibcode', u'1984A&A...141..309B'),
                            (u'@score', u'1'),
                            (u'@arxid', u''),
                            (u'@doi', u''),
                            ('#text', u'1984A&A...141..309B')]),
               OrderedDict([(u'@origin', u'ISI'),
                            (u'@bibcode', u'1984MNRAS.208..111S'),
                            (u'@score', u'1'),
                            (u'@arxid', u''),
                            (u'@doi', u''),
                            ('#text', u'1984MNRAS.208..111S')])])]) 
RELATIONS = OrderedDict([(u'@origin', u'ADS metadata'),
             (u'@type', u'relations'),
             (u'@primary', u'False'),
             (u'@alternate_journal', u'False'),
             (u'alternates', None),
             (u'links',
              OrderedDict([(u'link',
                            [OrderedDict([(u'@url',
                                           u'http://$NED$/cgi-bin/nph-objsearch?search_type=Search&refcode=1985A%26A...142....1K'),
                                          (u'@count', u'1'),
                                          (u'@type', u'ned')]),
                             OrderedDict([(u'@url',
                                           u'http://adsabs.harvard.edu/abs/1985A%26A...142....1K'),
                                          (u'@type', u'ADSlink')])])]))])
 
GENERAL_ENFORCED = {'abstracts': [{'lang': u'en',
   'origin': u'AAS',
   'text': u'We present analysis of polycyclic aromatic hydrocarbon (PAH) emission in mid-infrared spectra of a large sample of Herbig Ae and Be (HAeBe) stars. The spectra were obtained with the Infrared Spectrograph on the Spitzer Space Telescope. In a previous study of 18 HAeBe stars we found: evidence that the PAH ionization fraction in the circumstellar material around HAeBe stars is related to the structure of the PAH molecules; that the center wavelengths of the PAH emission features change systematically with stellar effective temperature changes; and that HAeBe stars have may have unique mid-infrared spectral characteristics that distinguish them from other strong PAH emission sources. We also found no simple correlation between the integrated intensity of PAH emission from HAeBe stars and the geometry of their proto-planetary disks. We now have expanded the sample to include 50 stars using archival data from the Spitzer database. We present a similar analysis applied to the larger sample.'}],
 'arxivcategories': [],
 'authors': [{'affiliations': [u'Ithaca College'],
   'emails': [],
   'name': {'native': None,
    'normalized': u'Hyatt, J',
    'western': u'Hyatt, Jordan'},
   'number': u'1',
   'orcid': None,
   'type': u'regular'},
  {'affiliations': [u'Ithaca College'],
   'emails': [],
   'name': {'native': None,
    'normalized': u'Keller, L',
    'western': u'Keller, L. D.'},
   'number': u'2',
   'orcid': None,
   'type': u'regular'},
  {'affiliations': [u'Cornell University'],
   'emails': [],
   'name': {'native': None,
    'normalized': u'Sloan, G',
    'western': u'Sloan, G. C.'},
   'number': u'3',
   'orcid': None,
   'type': u'regular'},
  {'affiliations': [u'Ithaca College'],
   'emails': [],
   'name': {'native': None,
    'normalized': u'Geidel, K',
    'western': u'Geidel, K. L.'},
   'number': u'4',
   'orcid': None,
   'type': u'regular'}],
 'comment': [],
 'conf_metadata': {'content': None, 'origin': u'AAS'},
 'copyright': [],
 'doi': [],
 'isbns': [],
 'issns': [],
 'keywords': [],
 'language': '',
 'publication': {'altbibcode': u'2010AAS...21542816H',
  'dates': [{'content': u'2010-01-00', 'type': u'date-published'},
   {'content': u'2010', 'type': 'publication_year'}],
  'electronic_id': u'428.16',
  'issue': None,
  'name': {'canonical': u'American Astronomical Society Meeting Abstracts #215',
   'raw': u'American Astronomical Society, AAS Meeting #215, #428.16; <ALTJOURNAL>Bulletin of the American Astronomical Society, Vol. 42, p.347</ALTJOURNAL>'},
  'origin': u'AAS',
  'page': None,
  'page_count': None,
  'page_last': None,
  'page_range': None,
  'volume': u'215'},
 'pubnote': [],
 'tempdata': {'alternate_journal': False,
  'modtime': u'2012-08-06T19:12:47',
  'origin': u'AAS',
  'primary': True,
  'type': u'general'},
 'titles': [{'lang': u'en',
   'text': u'Characteristics Of Hydrocarbon Emission From Herbig Ae/be Stars'}]}

PROPERTIES_ENFORCED = {'ads_openaccess': True,
 'associates': [{'comment': u'Part  1',
   'content': u'1983IAUS..100...99V',
   'origin': u'ADS metadata'},
  {'comment': u'Part  2',
   'content': u'1984A&A...133..127K',
   'origin': u'ADS metadata'},
  {'comment': u'Part  3',
   'content': u'1985A&A...142....1K',
   'origin': u'ADS metadata'},
  {'comment': u'Part  4',
   'content': u'1985A&A...144..202K',
   'origin': u'ADS metadata'},
  {'comment': u'Part  5',
   'content': u'1988A&A...191..201V',
   'origin': u'ADS metadata'},
  {'comment': u'Part  6',
   'content': u'1988A&A...199...41V',
   'origin': u'ADS metadata'},
  {'comment': u'Part  7',
   'content': u'1988A&A...204...39V',
   'origin': u'ADS metadata'},
  {'comment': u'Part  8',
   'content': u'1989A&A...218...49V',
   'origin': u'ADS metadata'},
  {'comment': u'Part  9',
   'content': u'1989A&A...225..317V',
   'origin': u'ADS metadata'},
  {'comment': u'Part 11',
   'content': u'1991A&A...243...71V',
   'origin': u'ADS metadata'},
  {'comment': u'Part 10',
   'content': u'1993A&A...269...15V',
   'origin': u'ADS metadata'}],
 'bibgroups': [],
 'data_sources': [{'content': u'NED', 'origin': u'ADS metadata'}],
 'databases': [{'content': u'AST', 'origin': u'ADS metadata'}],
 'doctype': {'content': u'article', 'origin': u'ADS metadata'},
 'eprint_openaccess': False,
 'ocrabstract': False,
 'openaccess': True,
 'private': False,
 'pub_openaccess': False,
 'refereed': True,
 'tempdata': {'alternate_journal': False,
  'modtime': None,
  'origin': u'ADS metadata',
  'primary': False,
  'type': u'properties'},
 'vizier_tables': [{'content': u'Galaxies', 'origin': u'ADS metadata'},
  {'content': u'HII regions', 'origin': u'ADS metadata'},
  {'content': u'Optical', 'origin': u'ADS metadata'}]}

REFERENCES_ENFORCED = {'references': [{'arxid': u'',
   'bibcode': u'1981A&A....98..251B',
   'content': u'1981A&A....98..251B',
   'doi': u'',
   'extension': None,
   'origin': u'ISI',
   'score': u'1'},
  {'arxid': u'',
   'bibcode': u'1981ApJ...246..666T',
   'content': u'1981ApJ...246..666T',
   'doi': u'',
   'extension': None,
   'origin': u'ISI',
   'score': u'1'},
  {'arxid': u'',
   'bibcode': u'1981ApJ...246L.105H',
   'content': u'1981ApJ...246L.105H',
   'doi': u'',
   'extension': None,
   'origin': u'ISI',
   'score': u'1'},
  {'arxid': u'',
   'bibcode': u'1981MNRAS.196..747H',
   'content': u'1981MNRAS.196..747H',
   'doi': u'',
   'extension': None,
   'origin': u'ISI',
   'score': u'1'},
  {'arxid': u'',
   'bibcode': u'1982A&A...114..400H',
   'content': u'1982A&A...114..400H',
   'doi': u'',
   'extension': None,
   'origin': u'ISI',
   'score': u'1'},
  {'arxid': u'',
   'bibcode': u'1982ApJ...252..125T',
   'content': u'1982ApJ...252..125T',
   'doi': u'',
   'extension': None,
   'origin': u'ISI',
   'score': u'1'},
  {'arxid': u'',
   'bibcode': u'1982ApJ...256..460K',
   'content': u'1982ApJ...256..460K',
   'doi': u'',
   'extension': None,
   'origin': u'ISI',
   'score': u'1'},
  {'arxid': u'',
   'bibcode': u'1982ApJ...258...64A',
   'content': u'1982ApJ...258...64A',
   'doi': u'',
   'extension': None,
   'origin': u'ISI',
   'score': u'1'},
  {'arxid': u'',
   'bibcode': u'1983MNRAS.202...37S',
   'content': u'1983MNRAS.202...37S',
   'doi': u'',
   'extension': None,
   'origin': u'ISI',
   'score': u'1'},
  {'arxid': u'',
   'bibcode': u'1983MNRAS.202.1001B',
   'content': u'1983MNRAS.202.1001B',
   'doi': u'',
   'extension': None,
   'origin': u'ISI',
   'score': u'1'},
  {'arxid': u'',
   'bibcode': u'1984A&A...141..309B',
   'content': u'1984A&A...141..309B',
   'doi': u'',
   'extension': None,
   'origin': u'ISI',
   'score': u'1'},
  {'arxid': u'',
   'bibcode': u'1984MNRAS.208..111S',
   'content': u'1984MNRAS.208..111S',
   'doi': u'',
   'extension': None,
   'origin': u'ISI',
   'score': u'1'}],
 'tempdata': {'alternate_journal': False,
  'modtime': u'2011-04-08T16:22:18',
  'origin': u'ISI',
  'primary': False,
  'type': u'references'}}



RELATIONS_ENFORCED = {'alternates': [],
 'links': [{'access': None,
   'count': u'1',
   'origin': None,
   'title': None,
   'type': u'ned',
   'url': u'http://$NED$/cgi-bin/nph-objsearch?search_type=Search&refcode=1985A%26A...142....1K'}],
 'preprints': [],
 'tempdata': {'alternate_journal': False,
  'modtime': None,
  'origin': u'ADS metadata',
  'primary': False,
  'type': u'relations'}}

RECORDS=[]

INPUT_DOC = {'JSON_fingerprint': u'fake_fingerprint',
 'adsdata': {'boost': u'0.52',
  'citation_count': 12,
  'citations': [u'2014JNuM..455...10C', u'2014JNuM..455...10D'],
  'grants': [{'agency': u'NASA', 'grant': u'123456-78'},
   {'agency': u'NSF-AST', 'grant': u'0618398'}],
  'norm_cites': u'5002',
  'read_count': u'50',
  'readers': [u'abaesrwersdlfkjsd', u'asfasdflkjsdfsldj'],
  'simbad_objects': [{'id': '5', 'type': 'type1'},
   {'id': '3000001', 'type': 'type2'}],
  'ned_objects': [{'id': 'foo bar', 'type': 'type1'},
   {'id': 'X+1-5 =6', 'type': 'type2'}]},
 'bibcode': u'testbibcode',
 'id': 99999999,
 'metadata': {'general': {'abstracts': [{'lang': '',
     'origin': u'some origin',
     'text': u"all no-skysurvey q'i quotient"}],
   'authors': [{'affiliations': [],
     'emails': [],
     'name': {'native': '',
      'normalized': u'T Hooft, V',
      'western': u"t'Hooft, van X"},
     'number': u'1',
     'orcid': '',
     'type': ''},
    {'affiliations': [u'NASA Kavli space center, Cambridge, MA 02138, USA'],
     'emails': [u'anders@email.com'],
     'name': {'native': '',
      'normalized': u'Anders, J M',
      'western': u'Anders, John Michael'},
     'number': u'2',
     'orcid': '',
     'type': ''},
    {'affiliations': [u'Einsteininstitute, Zurych, Switzerland'],
     'emails': [],
     'name': {'native': '',
      'normalized': u'Einstein, A',
      'western': u'Einstein, A'},
     'number': u'3',
     'orcid': '',
     'type': ''}],
   'doi': [{'content': u'doi:\xc5\xbd\xc5\xa0\xc4\x8c\xc5\x98\xc4\x8e\xc5\xa4\xc5\x87:123456789',
     'origin': ''}],
   'keywords': [{'channel': '',
     'normalized': u'stat mech',
     'origin': '',
     'original': u'Classical Statistical mechanics',
     'type': u'PACS Codes'}],
   'publication': {'dates': [{'content': u'2013-08-05',
      'type': u'date-published'}],
    'issue': u'24i',
    'origin': '',
    'page': u'2056-2078',
    'volume': u'l24'},
   'titles': [{'lang': u'en', 'text': u'This is of the title'},
    {'lang': '', 'text': u'This is of the alternate'}]},
  'properties': {'ads_openaccess': True,
   'bibgroups': [{'content': u'Cfa', 'origin': ''}],
   'databases': [{'content': u'phy', 'origin': ''},
    {'content': u'ast', 'origin': ''}],
   'doctype': {'content': u'Catalog', 'origin': ''},
   'eprint_openaccess': False,
   'ocrabstract': True,
   'openaccess': True,
   'private': False,
   'pub_openaccess': False,
   'refereed': False},
  'references': [{'bibcode': u'2014JNuM..455...10R',
    'content': '',
    'doi': '',
    'extension': '',
    'origin': '',
    'score': '1'},
   {'bibcode': u'2014JNuM..455...10T',
    'content': '',
    'doi': '',
    'extension': '',
    'origin': '',
    'score': '5'}],
  'relations': {'links': [{'access': None,
     'count': '78',
     'origin': None,
     'title': None,
     'type': 'ned',
     'url': 'http://$NED$/cgi-bin/nph-objsearch?search_type=Search&refcode=2013A%26A...552A.143S'},
    {'access': 'open',
     'count': None,
     'origin': None,
     'title': None,
     'type': 'postscript',
     'url': 'http://www.aanda.org/10.1051/0004-6361/201321247/postscript'},
    {'access': 'open',
     'count': None,
     'origin': None,
     'title': None,
     'type': 'electr',
     'url': 'http://dx.doi.org/10.1051%2F0004-6361%2F201321247'},
    {'access': None,
     'count': '74',
     'origin': None,
     'title': None,
     'type': 'simbad',
     'url': 'http://$SIMBAD$/simbo.pl?bibcode=2013A%26A...552A.143S'},
    {'access': 'open',
     'count': None,
     'origin': None,
     'title': None,
     'type': 'pdf',
     'url': 'http://www.aanda.org/10.1051/0004-6361/201321247/pdf'}],
   'preprints': [{'content': u'arxiv:1234.5678', 'ecode': '', 'origin': ''},
    {'content': u'ARXIV:hep-ph/1234', 'ecode': '', 'origin': ''}]}},
 'text': {'acknowledgment': {'content': '', 'modtime': '', 'provider': ''},
  'body': {'content': u'Some fulltext hashimoto',
   'language': '',
   'modtime': '',
   'provider': u'some provider'}}} 


EXPECTED_SOLR_DOC = {'abstract': u"all no-skysurvey q'i quotient",
 'aff': [u'-',
  u'NASA Kavli space center, Cambridge, MA 02138, USA',
  u'Einsteininstitute, Zurych, Switzerland'],
 'alternate_title': [u'This is of the alternate'],
 'author': [u"t'Hooft, van X", u'Anders, John Michael', u'Einstein, A'],
 'author_count': 3,
 'author_facet': [u'T Hooft, V', u'Anders, J M', u'Einstein, A'],
 'author_facet_hier': [u'0/T Hooft, V',
  u"1/T Hooft, V/t'Hooft, van X",
  u'0/Anders, J M',
  u'1/Anders, J M/Anders, John Michael',
  u'0/Einstein, A',
  u'1/Einstein, A/Einstein, A'],
 'author_norm': [u'T Hooft, V', u'Anders, J M', u'Einstein, A'],
 'bibcode': u'testbibcode',
 'bibgroup': [u'Cfa'],
 'bibgroup_facet': [u'Cfa'],
 'bibstem': [u'bibco', u'bibcode'],
 'bibstem_facet': u'bibcode',
 'body': u'Some fulltext hashimoto',
 'citation': [u'2014JNuM..455...10C', u'2014JNuM..455...10D'],
 'citation_count': 2,
 'cite_read_boost': 0.52,
 'classic_factor': 5002,
 'database': [u'astronomy', u'physics'],
 'date': u'2013-08-05T00:30:00.000000Z',
 'doctype': u'catalog',
 'doctype_facet_hier': [u'0/Non-Article', u'1/Non-Article/Catalog'],
 'doi': [u'doi:\xc5\xbd\xc5\xa0\xc4\x8c\xc5\x98\xc4\x8e\xc5\xa4\xc5\x87:123456789'],
 'email': [u'-', u'anders@email.com', u'-'],
 'first_author': u"t'Hooft, van X",
 'first_author_facet_hier': [u'0/T Hooft, V', u"1/T Hooft, V/t'Hooft, van X"],
 'first_author_norm': u'T Hooft, V',
 'grant': [u'NASA', u'123456-78', u'NSF-AST', u'0618398'],
 'grant_facet_hier': [u'0/NASA',
  u'1/NASA/123456-78',
  u'0/NSF-AST',
  u'1/NSF-AST/0618398'],
 'id': 99999999,
 'identifier': [u'arxiv:1234.5678',
  u'doi:\xc5\xbd\xc5\xa0\xc4\x8c\xc5\x98\xc4\x8e\xc5\xa4\xc5\x87:123456789',
  u'ARXIV:hep-ph/1234'],
 'issue': u'24i',
 'keyword': [u'Classical Statistical mechanics'],
 'keyword_facet': [u'stat mech'],
 'keyword_norm': [u'stat mech'],
 'keyword_schema': [u'PACS Codes'],
 'links_data': [u'{"access": "", "instances": "78", "title": "", "type": "ned", "url": "http://$NED$/cgi-bin/nph-objsearch?search_type=Search&refcode=2013A%26A...552A.143S"}',
  u'{"access": "open", "instances": "", "title": "", "type": "postscript", "url": "http://www.aanda.org/10.1051/0004-6361/201321247/postscript"}',
  u'{"access": "open", "instances": "", "title": "", "type": "electr", "url": "http://dx.doi.org/10.1051%2F0004-6361%2F201321247"}',
  u'{"access": "", "instances": "74", "title": "", "type": "simbad", "url": "http://$SIMBAD$/simbo.pl?bibcode=2013A%26A...552A.143S"}',
  u'{"access": "open", "instances": "", "title": "", "type": "pdf", "url": "http://www.aanda.org/10.1051/0004-6361/201321247/pdf"}'],
 'nedid': [u'foo bar', u'X+1-5 =6'],
 'nedtype': [u'Other'],
 'ned_object_facet_hier': [u'0/Other',
    u'1/Other/foo bar',
    u'0/Other',
    u'1/Other/X+1-5 =6'],
 'orcid_pub': [u'-', u'-', u'-'],
 'page': [u'2056-2078'],
 'property': [u'OPENACCESS',
  u'OCRABSTRACT',
  u'ADS_OPENACCESS',
  u'NONARTICLE',
  u'NOT REFEREED'],
 'pubdate': u'2013-08-05',
 'read_count': 2,
 'reader': [u'abaesrwersdlfkjsd', u'asfasdflkjsdfsldj'],
 'reference': [u'2014JNuM..455...10R'],
 'simbad_object_facet_hier': [u'0/Other',
  u'1/Other/5',
  u'0/Other',
  u'1/Other/3000001'],
 'simbid': [5, 3000001],
 'simbtype': [u'Other'],
 'title': [u'This is of the title', u'This is of the alternate'],
 'volume': u'l24'}

  
# used to check lower level database read code
# data is ingested into postgres so must have all non-nullable fields defined
INPUT_SQL_DOC = [{'bibcode': u'testbibcode2', 'simbad_objects': ['5 type1', '3000001 type2'],
                  'citations': [u'2014JNuM..455...10C', u'2014JNuM..455...10D'],
                  'readers': [u'abaesrwersdlfkjsd', u'asfasdflkjsdfsldj'],
                  'grants': [u'NASA 123456-78', 'NSF-AST 0618398'],
                  'norm_cites': u'5002', 'boost': u'0.52'},

                  {'bibcode': u'2000A&AS..143...41K_test', 'simbad_objects': [],
                  'citations': [],'readers': [], 'grants':[],
                   'norm_cites': u'5002', 'boost': u'0.52'},

                  {'bibcode': u'testbibcode3', 'simbad_objects': ['5 type1', '3000001 type2'],
                  'citations': [u'2014JNuM..455...10C', u'2014JNuM..455...10D'],
                  'readers': [u'abaesrwersdlfkjsd', u'asfasdflkjsdfsldj'],
                  'grants': [u'NASA 123456-78', 'NSF-AST 0618398'],
                  'norm_cites': u'5002', 'boost': u'0.52'}
                 ]

# used during Solr document generation check, must match values for expected solr doc
INPUT_SQL_SOLR_CHECK = {'bibcode': u'testbibcode2', 'simbad_objects': ['5 type1', '3000001 type2'],
                  'citations': [u'2014JNuM..455...10C', u'2014JNuM..455...10D'],
                  'readers': [u'abaesrwersdlfkjsd', u'asfasdflkjsdfsldj'],
                  'grants': [u'NASA 123456-78', 'NSF-AST 0618398'],
                  'norm_cites': u'5002', 'boost': u'0.52'}

INPUT_SQL_SOLR_CHECK1 = {'bibcode': u'2000A&AS..143...41K_test', 'simbad_objects': [],
                  'citations': [],
                  'readers': [], 'grants':[]}

INPUT_SQL_SOLR_CHECK2 = {'bibcode': u'2014arXiv1406.4542H', 'simbad_objects': [],
                'authors': [u"t'Hooft, van X", u'Anders, John Michael', u'Einstein, A'],
                'citations': [],
                'readers': [],
                'grants': []}


ADSRECORDS = OrderedDict()
_path = os.path.abspath(os.path.join(__file__, '../ADSRecords/'))
for x in os.listdir(_path):
    x = os.path.join(_path, x)
    if not os.path.isfile(x):
        continue
    f = eval(open(x, 'r').read())
    ADSRECORDS[f['bibcode']] = f

MERGEDRECS = OrderedDict()
MERGEDRECS['2015ApJ...815..133S'] = {'abstract': u'In order to examine their relation to the host galaxy, the extraplanar dusts of six nearby galaxies are modeled, employing a three-dimensional Monte Carlo radiative transfer code. The targets are from the highly inclined galaxies that show dust-scattered ultraviolet halos, and the archival Galaxy Evolution Explorer FUV band images were fitted with the model. The observed images are generally well-reproduced by two dust layers and one light source layer, whose vertical and radial distributions have exponential profiles. We obtained several important physical parameters, such as star formation rate (SFR<SUB>UV</SUB>), face-on optical depth, and scale-heights. Three galaxies (NGC 891, NGC 3628, and UGC 11794) show clear evidence for the existence of an extraplanar dust layer. However, it is found that the remaining three targets (IC 5249, NGC 24, and NGC 4173) do not necessarily need a thick dust disk to model the ultraviolet (UV) halo, because its contribution is too small and the UV halo may be caused by the wing part of the GALEX point spread function. This indicates that the galaxy samples reported to have UV halos may be contaminated by galaxies with negligible extraplanar (halo) dust. The galaxies showing evidence of an extraplanar dust layer fall within a narrow range on the scatter plots between physical parameters such as SFR<SUB>UV</SUB> and extraplanar dust mass. Several mechanisms that could possibly produce the extraplanar dust are discussed. We also found a hint that the extraplanar dust scale-height might not be much different from the polycyclic aromatic hydrocarbon emission characteristic height.',
 'ack': u'J.H.S. is grateful to Yujin Yang, Dennis Zaritsky, and Ann Zabludoff for their valuable comments and discussion of the results.',
 'aff': [u'Korea Astronomy and Space Science Institute, 776 Daeduk-daero, Yuseong-gu, Daejeon, 305-348, Korea',
  u'Korea Astronomy and Space Science Institute, 776 Daeduk-daero, Yuseong-gu, Daejeon, 305-348, Korea; Astronomy and Space Science Major, Korea University of Science and Technology, 217 Gajeong-ro, Yuseong-gu, Daejeon, 305-350, Korea; Department of Astrophysical Sciences, Princeton University, Princeton NJ 08544, USA'],
 'alternate_bibcode': [u'2015arXiv151103789S'],
 'arxiv_class': [u'Astrophysics - Astrophysics of Galaxies'],
 'author': [u'Shinn, Jong-Ho', u'Seon, Kwang-Il'],
 'author_count': 2,
 'author_facet': [u'Shinn, J', u'Seon, K'],
 'author_facet_hier': [u'0/Shinn, J',
  u'1/Shinn, J/Shinn, Jong-Ho',
  u'0/Seon, K',
  u'1/Seon, K/Seon, Kwang-Il'],
 'author_norm': [u'Shinn, J', u'Seon, K'],
 'bibcode': u'2015ApJ...815..133S',
 'bibstem': [u'ApJ', u'ApJ...815'],
 'bibstem_facet': u'ApJ',
 'body': u"1. INTRODUCTION Galaxies evolve while circulating their mediums between disks and halos, through stellar winds and radiation, supernova explosions, dynamic interactions between galaxies, gravitational attraction toward the galactic plane, star formation by gravitational collapse, etc. (see Finkbeiner 2014). These circulating mediums thus contain important information regarding how energy is transported and how the raw material for star formation is distributed within galaxies and their surroundings. Dust is a circulating medium, and it plays several important roles. For instance, it attenuates the stellar light through the scattering and absorption processes and re-radiates the absorbed light in longer wavelengths to transform the spectral energy distribution of the galaxy (see Conroy 2013). The dust that is located above the galactic plane (say, z \u2273 a few percent of the galactic diameter), i.e., the extraplanar dust, is especially important in several aspects. First, its existence means that the dust is somehow elevated against or accreted by the galactic plane's gravity (see Howk 2012). Second, it may reveal the evolutionary connection between star-forming galaxies and starburst galaxies, where star formation activity can supply the force that defies the galactic plane's gravity. Third, it may hold some hints on the dust-supplying channel to the circumgalactic medium and the intergalactic medium, where the existence of dust was reported (e.g., Zaritsky 1994; Chelouche et al. 2007; McGee Balogh 2010; M\xe9nard et al. 2010; Peek et al. 2015). Fourth, its existence is intriguing when considering the possibility that the extraplanar warm ionized medium (or diffuse ionized gas, Haffner et al. 2009) could be substantially contaminated by dust-scattered H\u03b1 emission (see Seon Witt 2012). Extraplanar dust has been observed for many edge-on spiral galaxies. Edge-on galaxies reveal extraplanar dust through the extinction of background stellar light (Howk Savage 1997, 1999, 2000; Alton et al. 2000; Rossa Dettmar 2003; Thompson et al. 2004), the mid-infrared continuum (Burgdorf et al. 2007; Kaneda et al. 2009; Verstappen et al. 2013; Bocchio et al. 2015), and ultraviolet (UV) scattered light (Hodges-Kluck Bregman 2014; Seon et al. 2014). Indirect evidence from the emission of polycyclic aromatic hydrocarbon (PAH) was also reported (Irwin Madden 2006; McCormick et al. 2013). However, most previous studies analyzed the data without a physical modeling for the galaxy, and therefore it was hard to extract direct links between physical parameters. For example, the correlation study using the extraplanar PAH emission characteristic height, presented by McCormick et al. (2013), could have been misled by the dilution of a radiation field away from the galactic plane, because the PAH emission is excited by the absorption of starlight (Leger Puget 1984; Allamandola et al. 1989; Draine 2003) and hence the emission does not directly correspond to the actual PAH amount. It is also true that the scale-height of the scattered light above the galactic plane is not the same as the actual scale-height of the extraplanar dust layer. Recently, from a radiative transfer simulation of UV images, Seon et al. (2014) showed that the extraplanar dust of NGC 891 can properly be modeled by adding a geometrically thick dust layer. They derived several important physical parameters such as star formation rate (SFR) and dust scale-height, and listed two primary elevation mechanisms for extraplanar dust: stellar radiation pressure or (magneto-)hydrodynamic flows (Greenberg et al. 1987; Ferrara et al. 1990; Howk Savage 1997). Here, we extend their approach to the highly inclined spiral galaxies with dust-scattered UV halos, discovered by Hodges-Kluck Bregman (2014), in order to investigate if there is any relation between the properties of extraplanar dust and the host galaxy. Six targets were analyzed, and three of them were found to need no additional thick dust disk in modeling the UV halos. The remaining three that did need the thick dust disk fall within a narrow range over the scatter plots between several physical parameters such as SFRUV and extraplanar dust mass. 2. TARGET, INSTRUMENT, AND DATA REDUCTION We are interested in modeling and characterizing extraplanar dust with several physical parameters. Seon et al. (2014) showed that the extraplanar dust of NGC 891 can be described by the exponential distributions of the starlight source and dust. Among the spiral galaxies studied by Hodges-Kluck Bregman (2014), we selected the galaxies that seem to be properly modeled with the exponential distributions. Those galaxies with ring structures or prominent spiral arms were excluded. Table 1 lists the six selected targets. Their distances, major axis sizes, stellar masses, and SFR ranges are \u223c5\u201375 Mpc, \u223c10\u201350 kpc, \u223c(0.1\u20137.0) \xd7 1010M\u2299, and \u223c0.1\u20135.0 M\u2299 yr\u22121, respectively. Table 1 Target Information Target Type i d D25 D25 M* SFRIR (\xb0) (Mpc) (\u2032) (kpc) (1010 M\u2299) (M\u2299 yr\u22121) (1) (2) (3) (4) (5) (6) (7) IC 5249 SBcd 90 29.70 3.63 31.36 0.15 \u22ef NGC 0024 Sc 70 7.24 5.75 12.12 0.15 0.11 NGC 0891 Sb 90 10.06 13.49 39.48 5.00 2.4 NGC 3628 Sb 79 10.95 14.79 47.11 7.00 4.8 NGC 4173 SBcd 90 7.83 5.01 11.41 \u22ef \u22ef UGC 11794 Sab 78 75.40 1.20 26.36 \u22ef 5.2 Typeset image Note. Columns: (1) morphological type, (2) disk inclination angle, (3) distance to the target, (4)\u2013(5) major axis size, (6) stellar mass, and (7) the star formation rate estimated from the infrared luminosity. Columns (1)\u2013(2) are taken from the HyperLeda galaxy database, http://leda.univ-lyon1.fr. Columns (3)\u2013(4) are taken from the NED database, http://ned.ipac.caltech.edu/. Column (5) is calculated with Columns (3) and (4). Columns (6)\u2013(7) are taken from Hodges-Kluck Bregman (2014). Column (6) is computed from the absolute K-band magnitude of the 2MASS catalog (Skrutskie et al. 2006) and the color corrections from Bell de Jong (2001). Column (7) is estimated from the relation between SFR and IR luminosity (Kennicutt 1998). The IR luminosity is measured using the Rice et al. (1988) relation and the IRAS catalog. We employed the archival data4 4 GR6/GR7; http://galex.stsci.edu/GR6/ of the Galaxy Evolution Explorer (GALEX ; Martin et al. 2005). GALEX was a satellite mission that performed all-sky imaging and spectroscopic surveys in two UV bands: FUV (\u223c1350\u20131750 \xc5) and NUV (\u223c1750\u20132750 \xc5). Table 2 shows more detailed information on GALEX. The archive provides fully reduced data, and the data reduction pipeline is described in Morrissey et al. (2007). We used the intensity maps, for which no background subtraction was applied during the data reduction. The FUV images were solely used to model the extraplanar dust, because the FUV band has a narrower bandwidth than the NUV band, and does not include the 2175 \xc5 bump that might cause the sudden variation of dust grain albedo (Figure 1, see. Draine 2003). Furthermore, the FUV image has a smaller number of foreground point sources than the NUV image, which makes the point-source masking process easier. Table 3 shows the exposure times of individual targets at each band; the NUV exposure time is also shown for reference. Figure 1. Albedo curve from the RV = 3.1 Milky Way dust model of Draine (2003) (solid) and the GALEX FUV/NUV effective area curves (dashed). Table 2 GALEX Information Band Bandwidth Effective Wavelength Field of View Image Resolution Image Pixel Scale (\xc5) (\xc5) (\xb0) (\u2032\u2032) (\u2032\u2032) FUV 1344\u20131786 1538.6 1.27 4.2 1.5 NUV 1771\u20132831 2315.7 1.25 5.3 1.5 Typeset image Note. All of the information is from Morrissey et al. (2007). Table 3 GALEX Exposure Time Target FUV NUV (s) (s) IC 5249 1705 4467 NGC 0024 1577 1577 NGC 0891 6047 6283 NGC 4173 1648 1648 NGC 7090 3007 3088 Typeset image In order to render the intensity maps to be suitable for two-dimensional fitting, we applied additional processes as follows. First, we masked point-like sources, employing the SExtractor (Bertin Arnouts 1996) output provided by the archive. Other remaining point-like sources were masked manually, and then the blank sky and the target galaxy were left intact. Second, we rotated the masked image for the major axis of the galaxy to be placed horizontally, and cropped the rotated image. The rotating and cropping were implemented using IRAF (Tody 1986, 1993). Finally, we subtracted the linear sky background that has a gradient along the galaxy's minor axis direction. This background was derived by fitting the averaged vertical profile of the cropped image with a linear function. During the fitting, we excluded the central part where the features from the galaxy and extraplanar diffuse sources are not negligible. Figure 2 shows the resultant FUV images and their vertical profiles, which reveal the existence of UV halos. Figure 2. GALEX FUV images and vertical profiles of our target galaxies. 3. ANALYSIS AND RESULTS 3.1. Fitting the GALEX FUV Images with a Three-dimensional Radiative Transfer Model We are interested in the physical properties of the extraplanar dust layer, such as the scale-height and the optical depth. Several physical parameters of the extraplanar dust layer are derived by exploiting the three-dimensional radiative transfer model to fit the GALEX FUV image processed as described in Section 2. We used a three-dimensional Monte Carlo radiative transfer code from Seon et al. (2014) that models multiple scatterings of photons in a cylindrical coordinate system. It uses the \u201cforced first scattering\u201d technique to enhance the calculation efficiency in optically thin media and the \u201cpeel-off\u201d technique to generate an image toward the observer (see Steinacker et al. 2013 for more about the computational acceleration techniques). The code also employs a fast voxel traversal algorithm (Amanatides et al. 1987), as implemented in Seon (2015). The model configuration was the same as in Seon et al. (2014). We adopted the axisymmetric distribution of dust and the starlight source, and their radial and vertical profiles follow the exponential curves.5 5 For the vertical profile, it may be hard to distinguish the exponential type from the power-law type, unless the signal-to-noise ratio is high enough at the distant area from the galactic plane. We note that a power-law radial profile was adopted in M\xe9nard et al. (2010) and Hodges-Kluck Bregman (2014). The dust component has two layers that share the same physical parameters, except for the scale-height and optical depth: one has a smaller scale-height (geometrically thin), while the other has a larger scale-height (geometrically thick). In brief, the following equations represent the dust and starlight distributions: 1 \u03ba ( r , z ) = \u03ba 0 thin exp \u2212 r h d \u2212 \u2223 z \u2223 z d thin + \u03ba 0 thick exp \u2212 r h d \u2212 \u2223 z \u2223 z d thick , for r \u2264 R d , z \u2264 Z d 0 , for r > R d , z > Z d ?> 2 I ( r , z ) = I 0 exp \u2212 r h s \u2212 \u2223 z \u2223 z s , for r \u2264 R s 0 , for r > R s . ?> \u03ba(r, z) and I(r, z) are the distributions of the extinction coefficient and the starlight source, respectively. We set the starlight wavelength to be the effective wavelength of the GALEX FUV band, 1538.6 \xc5 (Morrissey et al. 2007). r and z are the cylindrical coordinates. zs are the scale-heights of geometrically thin and thick dust layers, and starlight sources, respectively. hd and hs are the scale-lengths of the dust layer and starlight, respectively. r = 0, z = 0) of the thin and thick dust layers, respectively. Note that the optical depth along the symmetric axis is Rd and Rs are the truncation radii of the dust layers and the starlight, respectively. Zd is the truncation height of the dust distribution. For the light scattering calculation, we used the Henyey-Greenstein phase function (Henyey Greenstein 1941) and adopted the anisotropy parameter and albedo from the RV = 3.1 Milky Way dust model of Draine (2003) and Weingartner Draine (2001). The modeled image was convolved with the instrumental point spread function (PSF), before comparing with the processed GALEX FUV image. In the present paper, the observed images were not folded about the minor axis during the comparison, whereas those were folded in Seon et al. (2014). The model fitting was performed through \u03c72 minimization. We adopted an equal error for all image pixels to give equal weights for the disk and halo during the fitting, and the error was estimated from the pixel value fluctuation at backgrounds. Since 4 shows the best-fit model parameters for individual targets, and Figure 3 shows the corresponding model images. The \u03c72 differences between the minimum and its surrounding (\u03c3 uncertainties of scale-heights are much smaller than their step sizes. Figure 3. Fitting results. (Upper left) GALEX FUV image; (upper right) modeled image; (lower left) vertical profiles; (lower right) horizontal profiles. The profiles of the modeled image are black lines, while those of the GALEX FUV images are gray lines. (a)\u2013(f) Best-fit results for individual targets. Table 4 Fitting Parameters of the Best Fit for the GALEX FUV Images Target a a zs hd hs Rd b Zd Rs i SFRUV (kpc) (kpc) (kpc) (kpc) (kpc) (kpc) (kpc) (kpc) (\xb0) (M\u2299 yr\u22121) (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) IC 5249 0.375 2.600 0.562 0.013 0.208 9.3 122.5 15.7 5.0 15.7 90.2 0.57 (0.333) (0.218) (0.025) (1.0) (52.5) (0.7) (0.5) (0.3) (0.19) NGC 0024 0.175 3.100 0.443 1.002 0.146 0.8 1.3 12.5 5.0 12.5 78.1 0.079 (0.125) (0.778) (0.037) (0.1) (0.1) (2.8) (4.1) (0.6) (0.0036) NGC 0891 0.325 2.100 0.985 0.436 0.102 12.0 5.8 16.9 12.0 15.9 89.5 1.4 (0.412) (0.285) (0.014) (2.0) (0.9) (3.2) (1.6) (0.4) (0.34) NGC 3628 0.225 2.100 1.230 0.640 0.164 16.4 7.8 20.0 10.0 19.5 91.6 2.4 (1.115) (0.267) (0.127) (22.1) (13.6) (6.9) (1.5) (2.0) (1.3) NGC 4173 0.125 0.600 0.371 0.093 0.084 2.8 1.2 19.7 5.0 19.2 85.0 0.082 (0.365) (0.469) (0.373) (2.9) (1.9) (13.1) (10.8) (6.6) (0.020) UGC 11794 0.175 1.600 0.747 0.450 0.201 15.3 4.2 18.3 10.0 13.8 91.1 1.9 (0.686) (0.227) (0.174) (6.2) (2.9) (2.5) (2.9) (8.0) (1.7) Typeset image Notes. The numbers surrounded by parentheses in the table body are the corresponding uncertainties derived from the area half a z-step away from the best-fit (B-band optical depth along the symmetric axis of the thin dust disk, (4) the B-band optical depth along the symmetric axis of the thick dust disk, (5) the scale-height of the stellar disk, (6) the scale-length of the thin and thick dust disks, (7) the scale-length of the stellar disk, (8) the radial extent of the thin and thick dust disks, (9) the vertical extent of the thin and thick dust disks, (10) the radial extent of the stellar disk, (11) the disk inclination angle measured from the top of the image downward (see Figure 2), and (12) the star formation rate estimated from the intrinsic ultraviolet luminosity. a We covered several ( b This parameter is fixed during the fitting. The best-fit models have 1998, 1999; Alton et al. 2004; De Geyter et al. 2014). 1998, 1999; Alton et al. 2004; De Geyter et al. 2014). zs ranges from \u223c0.1 to 0.2 kpc, which is lower than the values from previous optical studies (\u223c0.2\u20130.5 kpc; Xilouris et al. 1998, 1999). This may reflect the fact that early-type stars, which are bright in UV, have a lower scale-height than late-type stars (e.g., Bahcall Soneira 1980; Wainscoat et al. 1992). The SFR was estimated from the intrinsic UV luminosity, employing the Starburst99 (Leitherer et al. 1999). The Salpeter initial mass function was assumed when calculating the UV luminosity per unit SFR. We also assumed that our sample galaxies are in a steady and continuous star-forming phase. The derived SFRs (SFRUV) are comparable with the SFRs derived from the infrared luminosity (SFRIR, Figure 4),6 6 SFRIR is omitted for IC 5249 and NGC 4173 because there is no far-infrared data that can be used in the SFR estimation (see Table 1). For example, they are not listed in the catalogs of Herschel and AKARI. although SFRUV is a little lower than SFRIR. We note that the estimated SFRUV includes some uncertainties, in the sense that the Starburst99 model is based on several (probable) assumptions, for instance, in star formation history and metallicity, and the assumption we made in the radiative transfer modeling\u2014smooth distribution of dust and the light source\u2014is a simplified representation of galaxies. Figure 4. Comparison of SFR. The SFRUV is from the GALEX image fitting (Table 4), while the SFRIR is from the IR luminosity (Table 1). The dashed line indicates the 1-to-1 ratio. This plot shows only the targets that have the SFRIR information (see Table 1). The downward triangle indicates the upper limit of SFRIR. We note that the obtained fitting parameters for NGC 891 are generally comparable to the 2014). This shows that our parameter search method over (2015). IC 5249's hs is much larger than others, and this peculiarity may be related to its very flat appearance (Figure 3(a)). NGC 24 has the highest hd, SFRUV, and is the least edge-on. NGC 3628 has the highest SFRUV. It has many local features, but the global shape is well-reproduced by the model (Figure 3(d)). NGC 4173 has the lowest 3.1.1. Effects of Radially Extended PSF on the Model Fitting When observing astronomical objects, optical systems inevitably accompany scattered lights, which are characterized by the wing part of the PSF. It was recently claimed that a radially extended PSF should be used in the analyses if the low surface-brightness features around bright sources are the targets of interest (Sandin 2014, 2015); Sandin (2014) found that the PSF radius should be larger than 1.5 times the distance between the low surface-brightness feature and bright source. Some of our targets have UV halos that are extended up to \u223c150\u2032\u2032 from the galactic plane (see Figure 2), which is larger than the radius of the GALEX standard PSF (\u223c90\u2032\u2032). Therefore, we check if the extended wing part of the PSF could have significant effects on the model fitting. Since the extended PSF of GALEX does not exist, we synthesized an extended PSF from the radial profile of the standard PSF. We fitted the average radial profile of the standard PSF with two functions referenced from Racine (1996): Equation (6) of (Racine 1996, the Moffat function) for the core and Equation (7) of Racine (1996) for the wing. The fitting was performed on the standard PSF cutting at the radius of 60\u2032\u2032, due to the larger fluctuation at higher radius. Figure 5 shows the fit result, which extends up to the radius of 250\u2032\u2032. The ratio of the wing/core at the origin is about 2 \xd7 10\u22123, and the characteristic angular scales are 446 and 158 for the core and wing parts, respectively. From this extended radial profile, we made a synthetic, extended PSF whose radial extent reaches 250\u2032\u2032. Figure 5. Average radial profile of the GALEX FUV band PSF (solid) and the extrapolated wing part (dashed). In order to visualize the effects of the extended PSF on the galactic halo, we made plots of profiles averaged along the horizontal axes, as seen in Figure 6. The red dashed lines and the magenta solid lines are the best-fit model profiles, convoluted with the extended and standard PSFs, respectively, excluding the thick dust disk component (see Equation (1)). If the UV halo is caused by the extended PSF wing rather than extraplanar dust, the red dashed line must significantly be higher than the magenta solid line at the region above the background noise upper bound (black dotted line in Figure 6). We found that the red dashed lines are higher than the magenta solid line at the region below or marginally above the noise upper bound for all targets. This result seems to be due to the fact that the greatest contribution of the PSF wing part is already included in the standard PSF, whose radial extent is \u223c90\u2032\u2032, and that the background signal-to-noise ratio of GALEX FUV data is not high enough to reveal the extended wing contribution. Figure 6. Effects of the extended PSF on the model fitting. All lines are the horizontally averaged vertical profiles. The gray solid line is from the GALEX FUV data. The black solid line is from the best-fit model convoluted with the standard PSF. The magenta solid and red dashed lines are from the best-fit model convoluted with the standard and extended PSF, respectively, excluding the thick dust disk component (see Equation (1)). The dotted line indicates the upper bound of background noise. The vertical profiles of NGC 891, NGC 3628, and UGC 11794 clearly show the halo emission excess, which cannot be explained with the PSF wing. However, we found that the existence of a thick dust disk is questionable for the remaining three targets\u2014IC 5249, NGC 24, and NGC 4173. As Figure 6 shows, for these targets, the magenta solid line is hardly distinguishable from the black solid line, the profile from the best-fit model including both thin and thick dust disks (see Equation (1)) and being convoluted with the standard PSF. These targets have lower 4), which indicates a lower amount of extraplanar dust (see Section 3.2) and subsequently makes the two profiles indistinguishable. In the case of NGC 24, its less edge-on appearance makes the difference even weaker. These three targets were excluded from our analyses. We here note that some of the galactic UV halos reported by Hodges-Kluck Bregman (2014) may be explainable solely with the thin dust disk. The data profiles of IC 5249 and NGC 24 seen in Figure 6 show hints of extended, decreasing wing-like features, but with intensities comparable to or lower than the background upper bound. The feature for IC 5249 can be explained solely by the standard PSF wing. However, for NGC 24, the extended PSF seems to reproduce the profile better. It should be noted that the wing features caused by the PSF can be misidentified as extended UV halos, without the aid of detailed modeling that properly includes the PSF effects. 3.2. Extraplanar Dust and the Host-galaxy Radiation Since our main interest is to investigate the relation between properties of the extraplanar dust and the host galaxy, we first check whether or not there is any correlation between the extraplanar dust mass (Mext) and SFRUV. The extraplanar dust was defined to be the dust located outside a certain vertical distance (zx) from the galactic plane. We set zx to be 5% of the major axis size (D25); for example, NGC 891 has zx \u2243 2 kpc (see Table 5). Mext is estimated as follows. We integrate the extinction coefficient over the extraplanar volume, where 0 \u2264 r \u2264 Rd and zx \u2264 z \u2264 Zd (see Equation (1)). This returns a value proportional to \u03c4B hd2, which is converted to Mext using the extinction curve from the RV = 3.1 Milky Way dust model of Draine (2003) and Weingartner Draine (2001). Table 5 Adopted zx and Estimated Mext Target zx Mext (kpc) (M\u2299) NGC 0891 1.97 8.91e + 06 NGC 3628 2.36 1.64e + 07 UGC 11794 1.32 1.35e + 07 Typeset image The top-left panel of Figure 7 shows the scatter plot between SFRUV (Table 4) and Mext that is estimated as above (Table 5). For reference to galaxy luminosity, the scatter plot between Mext and the galactic stellar mass (7. Mext falls between 10\u22124\u22123Mext of NGC 891 (8.91 \xd7 106M\u2299 for 5) is \u223c40 times larger than that estimated by Alton et al. (2000), 2.1 \xd7 105M\u2299 for 2000) only modeled the geometrically thin dust disk. Their dust scale-height of 0.31 kpc is similar to our 4). Figure 7. Relation between physical parameters from the model fitting. The scatter plots of the extraplanar dust mass (dust mass of 1. The guide lines are shown in the upper right panel. The lower left panel is a scatter plot featuring the star formation rate surface density and the ratio of the thick dust disk scale-height over the major axis size. We check another relation between the obtained model parameters, which is thought to be scale-independent, referring to McCormick et al. (2013). The bottom left panel of Figure 7 shows a scatter plot between the SFRUV surface density (\u03a3SFR,UV) and the ratio of SFR,UV is calculated from SFRUV (Table 4) and D25 (Table 1). The present results seem to fit into the relationship found by McCormick et al. (2013) over a much larger SFR surface density (\u03a3SFR) dynamic range, although they used the PAH emission characteristic height instead of the dust scale-height. We cannot draw any conclusive results about the relation between the previously mentioned quantities, since the number of samples is too small (see Section 3.1.1). However, note that those quantities fall within a narrow range for all three targets (see Figure 7). 4. DISCUSSION In modeling the galactic UV halo radiation reported by Hodges-Kluck Bregman (2014) we found that three of our targets do not need any additional dust disk other than the typical thin dust disk (see Section 3.1.1). Hodges-Kluck Bregman (2014) showed low and high correlations of the specific halo UV luminosity with the specific SFR and the host-galaxy UV luminosity, respectively. Our result suggests that the relations found by Hodges-Kluck Bregman (2014) may include some contamination from the galaxies with negligible halo (extraplanar) dust. This also demonstrates how the radiative transfer modeling can contribute to the interpretation of the galactic UV halo radiation. Since the sample number is too small, it would be premature to make a definite statement based on the scatter plots between different physical quantities (Figure 7). However, even with three targets, Figure 7 shows that the quantities fall within a narrow range. We also note that the three targets with no clear evidence of a thick dust layer have a much lower SFRUV than the other targets (Table 4). These suggest that a common mechanism might regulate the behavior of extraplanar dust. First, we can point out the galactic radiation pressure as a plausible mechanism. This mechanism was previously studied by several authors (Chiao Wickramasinghe 1972; Pecker 1972, 1974; Greenberg et al. 1987; Barsella et al. 1989; Ferrara et al. 1990, 1991; Franco et al. 1991; Davies et al. 1998). They showed that dust grains can be elevated above the galactic plane and even escape from the galaxy via the radiation pressure, considering two dust species (silicate and graphite) and diverse dust sizes under various galactic radiation fields and environments. There is a hint from the wavelength-averaged radiation pressure coefficient 1991) that the difference of galactic spectral shape might not significantly alter the strength of the radiation pressure. If this is the case and our target galaxies share a similar grain size distribution, the main factor that determines Mext would be the galactic luminosity itself, rather than the spectral shape of the radiation field. Howk Savage (1997) listed other elevating mechanisms such as hydrodynamical phenomena, magnetic field effects, and dynamical instabilities. They exemplified galactic fountain flows (Bregman 1980; Houck Bregman 1990), Parker instability by horizontal magnetic field (Parker 1966), and vertical instability by non-axisymmetric potentials (Binney 1981; Mulder Hooimeyer 1984). However, we think that all three mechanisms have some difficulties in directly producing the observed global-and-diffuse UV halos (Hodges-Kluck Bregman 2014) because their activities are likely to be local, not widespread over the disk.7 7 Note that these three mechanisms might be applicable to the filamentary, vertical dust features discovered by Howk Savage (1997). In the case of galactic fountain, the hot gas that is shock-heated by supernova explosions may be able to spread dust over the galactic halo somewhat evenly due to its high mobility, if the dust dragging by the hot gas is strong enough.The galactic radiation may have some advantage in producing the global-and-diffuse UV halo, since the radiation propagates approximately plane-parallel away from the galactic plane. It should be noted that many UV bright features close to the galactic mid-plane were found to correlate with star-forming regions in the mid-plane, especially for NGC 891 (Seon et al. 2014). These bright, scattered features might be due to the local mechanisms, as for the filamentary absorption features observed by Howk Savage (1997). Another possible mechanism is dust accretion from the circumgalactic or intergalactic medium. The existence of dust in the circumgalactic and intergalactic medium has been known from previous studies (e.g., Zaritsky 1994; Chelouche et al. 2007; McGee Balogh 2010; M\xe9nard et al. 2010; Peek et al. 2015). Therefore, if this external dust accretes to the host galaxy by the gravitational attraction (see Oosterloo et al. 2007), the extraplanar dust can be formed for the host galaxy. However, it is not clear whether the accretion process can make the diffuse-and-global distribution of extraplanar dust, including the PAH molecules. We here note that the diffuse UV halo radiation reported by Hodges-Kluck Bregman (2014) can have some localized features that are unresolved by GALEX and Swift, whose spatial resolutions are \u223c2\u2032\u2032\u20135\u2032\u2032. Other relations between extraplanar dust and SFR can be seen from the study of McCormick et al. (2013). They investigated the extraplanar PAH emission of the nearby galaxies with winds or extraplanar diffuse ionized gas, and showed the high correlations between the galactic infrared flux and the extraplanar PAH flux (r = 0.89), and between \u03a3SFR and the ratio of PAH emission characteristic height over galactic major axis size (HePAH/D25, r = 0.93). We here note that the PAH emission strength does not indicate the PAH mass, as mentioned in Section 1, since the PAH emits infrared radiations absorbing UV and optical radiations (Leger Puget 1984; Allamandola et al. 1989; Draine 2003). It is therefore improper to directly compare their results with ours (Figure 7). However, HePAH might not be much different from SFR,UV, SFR and 2013). Our \u03a3SFR,UV (\u223c10\u22123M\u2299 yr\u22121 kpc\u22122) is located at the lower range of their \u03a3SFR, and thus a future study of combined targets may reveal the connection of extraplanar dust with star-forming and star-bursting galaxies. If we extend the targets to include the galaxies in the vicinity of intergalactic dust (e.g., Zaritsky 1994; Chelouche et al. 2007; McGee Balogh 2010; M\xe9nard et al. 2010; Peek et al. 2015), we could study the dust at whole scales, i.e., from circumgalactic to intergalactic scales. 5. CONCLUSIONS We modeled the extraplanar dust of six nearby galaxies, employing a three-dimensional radiative transfer Monte Carlo simulation code to investigate the relations with their host galaxies\u2019 properties. The targets were selected from highly inclined galaxies that show dust-scattered UV halos (Hodges-Kluck Bregman 2014), and archival GALEX FUV band images were used. The configurations of dust and starlight sources are the same as Seon et al. (2014). Two dust layers and one starlight source layer are assumed, and their radial and vertical distributions are all exponential. The FUV images of all six galaxies are well-reproduced from the modeling, and we obtained several important physical parameters, such as SFRUV, B-band face-on optical depth, and scale-height. However, we found that the UV halo of three targets (IC 5249, NGC 24, and NGC 4173) can be modeled with solely the typical thin dust disk, since the contribution from the thick dust disk is too small. These three targets were excluded from our analyses, and we made scatter plots between several physical quantities for the remaining three targets (NGC 891, NGC 3628, and UGC 11794). Although the sample number is small, the data points fall within a narrow range in the scatter plots between Mext, SFRUV, SFR,UV. The needlessness of the thick dust disk for some galaxies reported to have UV halos by Hodges-Kluck Bregman (2014) indicates that the sample galaxies of Hodges-Kluck Bregman (2014) may be contaminated by galaxies with negligible extraplanar (halo) dust. This may thus affect the relations between the specific halo UV luminosity, the specific SFR, and the specific host-galaxy UV luminosity that they found. Although our sample number is just three, their narrow locations over the scatter plots suggest that a common mechanism may regulate the behavior of extraplanar dust. We list several possible mechanisms, discussing their ability to produce the observed diffuse-and-global UV halos. They are the galactic radiation, the (magneto-)hydrodynamic phenomena, and the dust accretion from the circumgalactic or intergalactic medium. The extraplanar PAH emission study of nearby galaxies by McCormick et al. (2013) could not be directly compared with ours, since the PAH emission does not simply mean the amount of PAH; the PAH emits infrared radiation by absorbing UV and optical radiations (Leger Puget 1984; Allamandola et al. 1989; Draine 2003). However, HePAH might not be much different from SFR,UV, SFR and 2013). Our \u03a3SFR,UV is at the lower end of McCormick et al.'s (2013) \u03a3SFR range, and hence we will be able to study the connection of extraplanar dust with the star-forming and starburst galaxies by extending our targets to include theirs.",
 'citation_count': 0,
 'data': [u'CDS', u'NED'],
 'data_facet': [u'CDS', u'NED'],
 'database': [u'astronomy'],
 'date': u'2015-12-01T00:00:00.000000Z',
 'doctype': u'article',
 'doctype_facet_hier': [u'0/Article', u'1/Article/Journal Article'],
 'doi': [u'10.1088/0004-637X/815/2/133'],
 'eid': u'133',
 'email': [u'jhshinn@kasi.re.kr', u'-'],
 'first_author': u'Shinn, Jong-Ho',
 'first_author_facet_hier': [u'0/Shinn, J', u'1/Shinn, J/Shinn, Jong-Ho'],
 'first_author_norm': u'Shinn, J',
 'identifier': [u'1511.03789',
  u'10.1088/0004-637X/815/2/133',
  u'2015arXiv151103789S'],
 'issue': u'2',
 'keyword': [u'dust',
  u'extinction',
  u'galaxies: halos',
  u'galaxies: ISM',
  u'galaxies: spiral',
  u'galaxies: star formation',
  u'radiative transfer',
  u'Astrophysics - Astrophysics of Galaxies'],
 'keyword_facet': [u'dust',
  u'ism dust extinction',
  u'galaxies halos',
  u'galaxies intergalactic medium',
  u'galaxies spiral',
  u'galaxies star clusters',
  u'radiative transfer'],
 'keyword_norm': [u'dust',
  u'ism dust extinction',
  u'galaxies halos',
  u'galaxies intergalactic medium',
  u'galaxies spiral',
  u'galaxies star clusters',
  u'radiative transfer',
  u'-'],
 'keyword_schema': [u'Astronomy',
  u'Astronomy',
  u'Astronomy',
  u'Astronomy',
  u'Astronomy',
  u'Astronomy',
  u'Astronomy',
  u'arXiv'],
 'links_data': [u'{"access": "", "instances": "7", "title": "", "type": "simbad", "url": "http://$SIMBAD$/simbo.pl?bibcode=2015ApJ...815..133S"}',
  u'{"access": "open", "instances": "", "title": "", "type": "pdf", "url": "http://stacks.iop.org/0004-637X/815/133/pdf"}',
  u'{"access": "", "instances": "6", "title": "", "type": "ned", "url": "http://ned.ipac.caltech.edu/cgi-bin/nph-objsearch?search_type=Search&refcode=2015ApJ...815..133S"}',
  u'{"access": "open", "instances": "", "title": "", "type": "preprint", "url": "http://arxiv.org/abs/1511.03789"}',
  u'{"access": "open", "instances": "", "title": "", "type": "electr", "url": "http://dx.doi.org/10.1088%2F0004-637X%2F815%2F2%2F133"}'],
 'orcid_pub': [u'0000-0001-7967-6473', u'0000-0001-9561-8134'],
 'page': [u'133'],
 'property': [u'OPENACCESS',
  u'REFEREED',
  u'EPRINT_OPENACCESS',
  u'PUB_OPENACCESS',
  u'ARTICLE'],
 'pub': u'The Astrophysical Journal',
 'pub_raw': u'The Astrophysical Journal, Volume 815, Issue 2, article id. 133, <NUMPAGES>14</NUMPAGES> pp. (2015).',
 'pubdate': u'2015-12-00',
 'pubnote': [u'33 pages, 7 figures, 5 tables, ApJ in press; doi:10.1088/0004-637X/815/2/133'],
 'read_count': 0,
 'reference': [u'1941ApJ....93...70H',
  u'1966ApJ...145..811P',
  u'1972A&A....18..253P',
  u'1972MNRAS.159..361C',
  u'1974A&A....35....7P',
  u'1980ApJ...236..577B',
  u'1980ApJS...44...73B',
  u'1981MNRAS.196..455B',
  u'1984A&A...134..158M',
  u'1984A&A...137L...5L',
  u'1986SPIE..627..733T',
  u'1987Natur.327..214G',
  u'1988ApJS...68...91R',
  u'1989A&A...209..349B',
  u'1989ApJS...71..733A',
  u'1990A&A...240..259F',
  u'1990ApJ...352..506H',
  u'1991ApJ...366..443F',
  u'1991ApJ...381..137F',
  u'1992ApJS...83..111W',
  u'1993ASPC...52..173T',
  u'1994AJ....108.1619Z',
  u'1996A&AS..117..393B',
  u'1996PASP..108..699R',
  u'1997AJ....114.2463H',
  u'1998A&A...331..894X',
  u'1998ApJ...498..541K',
  u'1998MNRAS.300.1006D',
  u'1999A&A...344..868X',
  u'1999AJ....117.2077H',
  u'1999ApJS..123....3L',
  u'2000A&AS..145...83A',
  u'2000AJ....119..644H',
  u'2001ApJ...548..296W',
  u'2001ApJ...550..212B',
  u'2003A&A...406..505R',
  u'2003ARA&A..41..241D',
  u'2004A&A...425..109A',
  u'2004AJ....128..662T',
  u'2005ApJ...619L...1M',
  u'2006A&A...445..123I',
  u'2006AJ....131.1163S',
  u'2007AJ....134.1019O',
  u'2007ApJ...668..918B',
  u'2007ApJ...671L..97C',
  u'2007ApJS..173..682M',
  u'2009ApJ...698L.125K',
  u'2009RvMP...81..969H',
  u'2010MNRAS.405.1025M',
  u'2010MNRAS.405.2069M',
  u'2012ApJ...758..109S',
  u'2013A&A...556A..54V',
  u'2013ARA&A..51...63S',
  u'2013ARA&A..51..393C',
  u'2013ApJ...774..126M',
  u'2014A&A...567A..97S',
  u'2014ApJ...785L..18S',
  u'2014ApJ...789..131H',
  u'2014MNRAS.441..869D',
  u'2014Sci...346..905F',
  u'2015A&A...577A.106S',
  u'2015ApJ...813....7P',
  u'2015JKAS...48...57S',
  u'2015arXiv150907677B'],
 'title': [u'Ultraviolet Radiative Transfer Modeling of Nearby Galaxies with Extraplanar Dusts'],
 'volume': u'815',
 'year': u'2015'}
 



INPUT_DOC1={
    "id" : 99999998,
    "modtime" : "2014-11-06T14:11:18.697474Z",
    "bibcode" : u"2000A&AS..143...41K_test",
    "JSON_fingerprint" : "{\"abs\":[{\"p\":\"/proj/ads/abstracts/ast/text/J20/J20-02694.abs\",\"primary\":1,\"t\":\"1317932566\"},{\"p\":\"/proj/ads/abstracts/ast/text/S20/S20-02694.abs\",\"t\":\"1347312274\"}],\"full\":[{\"p\":\"/proj/ads/fulltext/extracted/20/00/A&/AS/,,/14/3,/,,/41/K//meta.json\",\"t\":1395500064},{\"p\":\"/proj/ads/fulltext/extracted/20/00/A&/AS/,,/14/3,/,,/41/K//fulltext.txt\",\"t\":1363680233}],\"links\":{\"electr\":[{\"u\":\"http://dx.doi.org/10.1051%2Faas%3A2000170\"}],\"preprint\":[{\"u\":\"astro-ph/0002104\"}],\"spires\":[{\"u\":\"http://inspirehep.net/search?p=find+j+AAESB,143,41\"}]},\"prop\":[\"bibgroup: CfA\",\"refereed\"],\"refs\":[{\"p\":\"/proj/ads/references/resolved/A+AS/0143/iss1.raw.result\",\"t\":1374540245},{\"p\":\"/proj/ads/references/resolved/AUTHOR/Markus/MarkusMagic.pairs.result\",\"t\":1412026020},{\"p\":\"/proj/ads/references/resolved/ISI/A&AS/A&AS0143.isi.pairs.result\",\"t\":1414726893}]};{\"abs\":[{\"p\":\"/proj/ads/abstracts/pre/text/X00/X00-03262.abs\",\"primary\":1,\"t\":\"1257155059\"}],\"links\":{\"electr\":[{\"u\":\"http://dx.doi.org/10.1051%2Faas%3A2000170\"}],\"preprint\":[{\"u\":\"astro-ph/0002104\"}],\"spires\":[{\"u\":\"http://inspirehep.net/search?p=find+eprint+astro-ph/0002104\"}]},\"prop\":[\"bibgroup: CfA\"],\"refs\":[{\"p\":\"/proj/ads/references/resolved/astro-ph/2000/0002104.raw.result\",\"t\":1360840132}]}",

    "text": {},
    "metadata" : {
    "references": [],
    'properties': {'refereed': True, 'openaccess': False, 
                   'doctype': {'content': u'article', 'origin': u'ADS metadata'}, 
                   'private': False, 'ocrabstract': False, 
                   'ads_openaccess': False,
                   'eprint_openaccess': False,
                   'pub_openaccess': False,
                   'databases': [{'content': u'ast', 'origin': ''}], 
                   'bibgroups': [{'content': u'CfA', 'origin': ''}],
                   'data_sources': [{'content':u'foo','origin':u'bar'},{'content':u'foo2'}],
                   'vizier_tables': [{'content':u'tab1','origin':u'vizier'},{'content':u'tab2'}],
                   },
    "relations": {},
    "general" : {
        "comment" : [ ],
        "doi" : [
            {
                "origin" : u"A&AS",
                "content" : u"10.1051/aas:2000170"
                }
            ],
        "titles" : [
                {
                "lang" : u"en",
                "text" : u"The NASA Astrophysics Data System: Overview"
                }
            ],
        "publication" : {
            "origin" : u"A&AS",
            "dates" : [
                {
                    "content" : u"2000-04-00",
                    "type" : u"date-published"
                    },
                {
                    "content" : u"2000",
                    "type" : u"publication_year"
                    }
                ],
            "name" : {
                "raw" : u"Astronomy and Astrophysics Supplement, v.143, p.41-59",
                "canonical" : u"Astronomy and Astrophysics Supplement Series"
                },
            "page_count" : u"19",
            "page" : u"41",
            "volume" : u"143",
            "page_range" : u"41-59",
            "electronic_id" : u"here is the eid",
            "issue" : None,
            "page_last" : u"59"
            },
        "language" : u"",
        "issns" : [ ],
        "conf_metadata" : {
            "origin" : u"A&AS",
            "content" : None
            },
        "copyright" : [ ],
        "isbns" : [ ],
        "authors" : [
            {
                "name" : {
                    "native" : None,
                    "western" : u"Kurtz, Michael J.",
                    "normalized" : u"Kurtz, M"
                    },
                "number" : u"1",
                "affiliations" : [
                    u"Harvard-Smithsonian Center for Astrophysics, Cambridge, MA 02138, USA"
                    ],
                "orcid" : None,
                "type" : u"regular",
                "emails" : [ ]
                },
            {
                "name" : {
                    "native" : None,
                    "western" : u"Eichhorn, Guenther",
                    "normalized" : u"Eichhorn, G"
                    },
                "number" : u"2",
                "affiliations" : [
                    u"Harvard-Smithsonian Center for Astrophysics, Cambridge, MA 02138, USA"
                    ],
                "orcid" : None,
                "type" : u"regular",
                "emails" : [ ]
                },
            {
                "name" : {
                    "native" : None,
                    "western" : u"Accomazzi, Alberto",
                    "normalized" : u"Accomazzi, A"
                    },
                "number" : u"3",
                "affiliations" : [
                    u"Harvard-Smithsonian Center for Astrophysics, Cambridge, MA 02138, USA"
                    ],
                "orcid" : u"0000-0002-4110-3511",
                "type" : u"regular",
                "emails" : [ ]
                },
            {
                "name" : {
                    "native" : None,
                    "western" : u"Grant, Carolyn S.",
                    "normalized" : u"Grant, C"
                    },
                "number" : u"4",
                "affiliations" : [
                    u"Harvard-Smithsonian Center for Astrophysics, Cambridge, MA 02138, USA"
                    ],
                "orcid" : None,
                "type" : u"regular",
                "emails" : [ ]
                },
            {
                "name" : {
                    "native" : None,
                    "western" : u"Murray, Stephen S.",
                    "normalized" : u"Murray, S"
                    },
                "number" : u"5",
                "affiliations" : [
                    u"Harvard-Smithsonian Center for Astrophysics, Cambridge, MA 02138, USA"
                    ],
                "orcid" : None,
                "type" : u"regular",
                "emails" : [ ]
                },
            {
                "name" : {
                    "native" : None,
                    "western" : u"Watson, Joyce M.",
                    "normalized" : u"Watson, J"
                    },
                "number" : u"6",
                "affiliations" : [
                    u"Harvard-Smithsonian Center for Astrophysics, Cambridge, MA 02138, USA"
                    ],
                "orcid" : None,
                "type" : u"regular",
                "emails" : [ ]
                }
            ],
        "keywords" : [
            {
                "origin" : u"A&AS",
                "type" : u"Astronomy",
                "original" : u"METHODS: DATA ANALYSIS",
                "channel" : u"",
                "normalized" : u"methods data analysis"
                },
            {
                "origin" : u"A&AS",
                "type" : u"Astronomy",
                "original" : u"ASTRONOMICAL DATABASES: MISCELLANEOUS",
                "channel" : u"",
                "normalized" : None
                },
            {
                "origin" : u"A&AS",
                "type" : u"Astronomy",
                "original" : u"PUBLICATIONS: BIBLIOGRAPHY",
                "channel" : u"",
                "normalized" : None
                },
            {
                "origin" : u"A&AS",
                "type" : u"Astronomy",
                "original" : u"SOCIOLOGY OF ASTRONOMY",
                "channel" : u"",
                "normalized" : None
                },
            {
                "origin" : u"ARXIV",
                "type" : u"arXiv",
                "original" : u"Astrophysics",
                "channel" : u"astro-ph",
                "normalized" : u"astrophysics"
                }
            ],
        "arxivcategories" : [
            u"Astrophysics"
            ],
        "pubnote" : [
            {
                "origin" : u"ARXIV",
                "content" : u"19 pages, 22 figures; Astron.Astrophys.Suppl.Ser. 143 (2000) 41-59; doi:10.1051/aas:2000170"
                }
            ],
        "altpublications" : [
            {
                "origin" : u"ARXIV",
                "dates" : [
                    {
                        "content" : u"2000-02-00",
                        "type" : u"date-preprint"
                        },
                    {
                        "content" : u"2000",
                        "type" : u"publication_year"
                        }
                    ],
                "name" : {
                    "raw" : u"eprint arXiv:astro-ph/0002104",
                    "canonical" : u"ArXiv e-prints"
                    },
                "page_count" : None,
                "page" : None,
                "volume" : None,
                "page_range" : None,
                "electronic_id" : u"astro-ph/0002104",
                "altbibcode" : u"2000astro.ph..2104K",
                "issue" : None,
                "page_last" : None
                }
            ],
        }
    }
}

EXPECTED_SOLR_DOC1={
    "first_author": u"Kurtz, Michael J.",
#    "links_data": [u"{\"title\":\"\",\"type\":\"spires\",\"instances\":\"\"}", "{\"title\":\"\",\"type\":\"electr\",\"instances\":\"\"}", "{\"title\":\"\",\"type\":\"spires\",\"instances\":\"\"}"], 
    "first_author_norm": u"Kurtz, M", 
    "year": u"2000", 
    "bibcode": u"2000A&AS..143...41K_test", 
    "author_facet_hier": [
        u"0/Kurtz, M", u"1/Kurtz, M/Kurtz, Michael J.",
        u"0/Eichhorn, G", u"1/Eichhorn, G/Eichhorn, Guenther", 
        u"0/Accomazzi, A", u"1/Accomazzi, A/Accomazzi, Alberto", 
        u"0/Grant, C", u"1/Grant, C/Grant, Carolyn S.", 
        u"0/Murray, S", u"1/Murray, S/Murray, Stephen S.",
        u"0/Watson, J", u"1/Watson, J/Watson, Joyce M."], 
    "bibstem": [u"A&AS", u"A&AS..143"], 
    "aff": [
        u"Harvard-Smithsonian Center for Astrophysics, Cambridge, MA 02138, USA", 
        u"Harvard-Smithsonian Center for Astrophysics, Cambridge, MA 02138, USA", 
        u"Harvard-Smithsonian Center for Astrophysics, Cambridge, MA 02138, USA", 
        u"Harvard-Smithsonian Center for Astrophysics, Cambridge, MA 02138, USA",
        u"Harvard-Smithsonian Center for Astrophysics, Cambridge, MA 02138, USA", 
        u"Harvard-Smithsonian Center for Astrophysics, Cambridge, MA 02138, USA"], 
    "keyword": [u"METHODS: DATA ANALYSIS", 
                u"ASTRONOMICAL DATABASES: MISCELLANEOUS", 
                u"PUBLICATIONS: BIBLIOGRAPHY", 
                u"SOCIOLOGY OF ASTRONOMY", 
                u"Astrophysics"], 
    "keyword_norm": [u"methods data analysis", u"-", u"-", u"-",
                     u"astrophysics"], 
    "keyword_schema": [u"Astronomy", u"Astronomy",
                       u"Astronomy", u"Astronomy", u"arXiv"], 
    "keyword_facet": [u"methods data analysis",
                      u"astrophysics"], 
    "email": [u"-", u"-", u"-", u"-", u"-", u"-"],
    "orcid_pub": [u"-", u"-", u"0000-0002-4110-3511", u"-", u"-", u"-"],
    'data': [u'foo',u'foo2'],
    'data_facet': [u'foo',u'foo2'],
    "arxiv_class": [u"Astrophysics"], 
    "bibgroup": [u"CfA"],
    "bibgroup_facet": [u"CfA"],
    "author_facet": [u"Kurtz, M", u"Eichhorn, G",
                     u"Accomazzi, A", u"Grant, C", u"Murray, S", u"Watson, J"],
    "bibstem_facet": u"A&AS", 
    "pub": u"Astronomy and Astrophysics Supplement Series", 
    "volume": u"143", 
    "doi": [u"10.1051/aas:2000170"],
    "eid": u"here is the eid",
    "author_norm": [u"Kurtz, M", u"Eichhorn, G", u"Accomazzi, A", u"Grant, C",
                    u"Murray, S", u"Watson, J"], 
    "date": u"2000-04-01T00:00:00.000000Z",
    "pubdate": u"2000-04-00", 
    "id": 99999998,
    "identifier": [u"10.1051/aas:2000170"],
    "database": [u"astronomy"], 
    "author":
        [u"Kurtz, Michael J.", u"Eichhorn, Guenther", u"Accomazzi, Alberto",
         u"Grant, Carolyn S.", u"Murray, Stephen S.", u"Watson, Joyce M."],
    "author_count": 6,
    "citation_count": 0, 
    "pub_raw": u"Astronomy and Astrophysics Supplement, v.143, p.41-59", 
#    "cite_read_boost": 0.45,
    "first_author_facet_hier": [u"0/Kurtz, M", u"1/Kurtz, M/Kurtz, Michael J."], 
    "title": [u"The NASA Astrophysics Data System: Overview"],
    "property": [u"REFEREED", u"ARTICLE"], 
    "page": [u"41",u"here is the eid"],
    'vizier':[u'tab1',u'tab2'],
    'vizier_facet':[u'tab1',u'tab2'],
    "read_count": 0,
    'doctype': u'article',
    'doctype_facet_hier': [u'0/Article', u'1/Article/Journal Article'],
    'pubnote': [u'19 pages, 22 figures; Astron.Astrophys.Suppl.Ser. 143 (2000) 41-59; doi:10.1051/aas:2000170']
}

INPUT_DOC2={
    "id" : 99999997,
    "modtime" : '2014-06-18T21:06:49',
    'bibcode' : u'2014arXiv1406.4542H',
    "text": {},
    "metadata" : {
        "references": [],
        'properties': {'refereed': False, 'openaccess': True, 
                       'doctype': {'content': u'article', 'origin': u'ADS metadata'}, 
                       'private': False, 'ocrabstract': False, 'ads_openaccess':False,
                       'eprint_openaccess': True, 'pub_openaccess': False
                   },
        "relations": {},
        "general" : {
            "publication" : {
                "origin" : u"ARXIV",
                'dates' : [
                    {
                        'type' : u'date-preprint',
                        'content' : u'2014-06-00'
                        }
                    ]
                },
            'authors': [
                {'name': {'normalized': u'T Hooft, V', 'western': u"t'Hooft, van X", 'native': ''}, 
                 'number': u'1', 'affiliations': [], 'orcid': '', 'type': '', 'emails': []}, 
                {'name': {'normalized': u'Anders, J M', 'western': u'Anders, John Michael', 'native': ''}, 
                 'number': u'2', 'affiliations': [u'NASA Kavli space center, Cambridge, MA 02138, USA'], 
                 'orcid': '', 'type': '', 'emails': [u'anders@email.com']}, 
                {'name': {'normalized': u'Einstein, A', 'western': u'Einstein, A', 'native': ''}, 
                 'number': u'3', 'affiliations': [u'Einsteininstitute, Zurych, Switzerland'], 
                 'orcid': '', 'type': '', 'emails': []}],
            }
        },
    'orcid_claims': {'verified': [u'-', u'1111-2222-3333-4444', u'-']}
    }


EXPECTED_SOLR_DOC2={
    "id" : 99999997,
    'bibcode' : u'2014arXiv1406.4542H',
    'date':     u'2014-06-01T00:00:00.000000Z',
    'bibstem': [u'arXiv', u'arXiv1406'],
    'bibstem_facet': u'arXiv',
    'pubdate' : u'2014-06-00',
    "property": [u"OPENACCESS", u"EPRINT_OPENACCESS", u"ARTICLE", u"NOT REFEREED"], 
    "read_count": 0,
    "citation_count": 0,
    'doctype': u'article',
    
    'aff': [u'-',
          u'NASA Kavli space center, Cambridge, MA 02138, USA',
          u'Einsteininstitute, Zurych, Switzerland'],
   'author': [u"t'Hooft, van X", u'Anders, John Michael', u'Einstein, A'],
   'author_facet': [u'T Hooft, V', u'Anders, J M', u'Einstein, A'],
   'author_facet_hier': [u'0/T Hooft, V',
                         u"1/T Hooft, V/t'Hooft, van X",
                         u'0/Anders, J M',
                         u'1/Anders, J M/Anders, John Michael',
                         u'0/Einstein, A',
                         u'1/Einstein, A/Einstein, A'],
   'author_norm': [u'T Hooft, V', u'Anders, J M', u'Einstein, A'],
    'email': [u'-', u'anders@email.com', u'-'],
    'first_author': u"t'Hooft, van X",
    'first_author_facet_hier': [u'0/T Hooft, V', u"1/T Hooft, V/t'Hooft, van X"],
    'first_author_norm': u'T Hooft, V',
    'orcid_pub': [u'-', u'-', u'-'],
    'orcid_user': [u'-', u'1111-2222-3333-4444', u'-'],
    'author_count': 3,
    'doctype_facet_hier': [u'0/Article', u'1/Article/Journal Article']
}

