MERGER_RULES = {
  'default':              'stringConcatenateMerger',

  #<metadata type="general">
  'creation_time':        'stringConcatenateMerger', #Also in <metadata type="references">
  'modification_time':    'stringConcatenateMerger', #Also in <metadata type="references">
  'arxivcategories':      'originTrustMerger',
  'keywords':             'originTrustMerger',
  'title':                'originTrustMerger',
  'abstract':             'originTrustMerger',
  'author':               'originTrustMerger',
  'pagenumber':           'originTrustMerger',
  'journal':              'originTrustMerger',
  'canonical_journal':    'originTrustMerger',
  'volume':               'originTrustMerger',
  'issue':                'originTrustMerger',
  'dates':                'originTrustMerger',
  'page_range':           'originTrustMerger',
  'page':                 'originTrustMerger',
  'lastpage':             'originTrustMerger',
  'electronic_id':        'originTrustMerger',
  'conf_metadata':        'originTrustMerger',
  'isbns':                'takeAll',
  'issns':                'takeAll',
  'DOI':                  'originTrustMerger',
  'origin':               'originTrustMerger',
  'instruments':          'takeAll',
  'copyright':            'originTrustMerger',
  'objects':              'takeAll',
  'language':             'originTrustMerger',

  #<metadata type="properties">
  'databases':            'takeAll',
  'JSON_timestamp':       'stringConcatenateMerger',
  'pubtype':              'originTrustMerger',
  'bibgroups':            'takeAll',
  'openaccess':           'originTrustMerger',
  'private':              'originTrustMerger',
  'pubtype':              'originTrustMerger',
  'bibgroups':            'takeAll',
  'openaccess':           'originTrustMerger',
  'nonarticle':           'originTrustMerger',
  'ocrabstract':          'originTrustMerger',
  'openaccess':           'originTrustMerger',
  'private':              'originTrustMerger',
  'refereed':             'originTrustMerger',

  #<metadata type="references">
  'reference':            'referencesMerger',

  #<metadata type="relations">
  'preprintid':           'takeAll',
  'alternatives':         'takeAll',
  'associates':           'takeAll',
  'links':                'takeAll',
}

__PRIORITIES_DEFAULT = {
  10: ['ADS METADATA',],
  1.0: ['ISI'],
  0.5: ['A&A', 'A&AS', 'A&G', 'AAO', 'AAS', 'AASP', 'AAVSO', 'ACA',
      'ACASN', 'ACHA', 'ACTA', 'ADASS', 'ADIL', 'ADS', 'AFRSK', 'AG',
      'AGDP', 'AGU', 'AIP', 'AJ', 'ALMA', 'AMS', 'AN', 'ANRFM', 'ANRMS',
      'APJ', 'APS', 'ARA&A', 'ARAA', 'ARAC', 'AREPS', 'ARNPS', 'ASBIO',
      'ASD', 'ASL', 'ASP', 'ASPC', 'ASTL', 'ASTRON', 'ATEL', 'ATSIR',
      'AUTHOR', 'OTHER', 'BAAA', 'BAAS', 'BALTA', 'BASBR', 'BASI', 'BAVSR', 'BEO',
      'BESN', 'BLAZ', 'BLGAJ', 'BOTT', 'BSSAS', 'CAPJ', 'CBAT', 'CDC',
      'CEAB', 'CFHT', 'CHAA', 'CHANDRA', 'CHJAA', 'CIEL', 'COAST',
      'COPERNICUS', 'COSKA', 'CSCI', 'CUP', 'CXC', 'CXO', 'DSSN',
      'E&PSL', 'EDP', 'EDP SCIENCES', 'KONKOLY', 'EJTP', 'ELSEVIER', 'ESA', 'ESO', 'ESP', 'EUVE',
      'FCPH', 'FUSE', 'GCN', 'GJI', 'GRG', 'HISSC', 'HST', 'HVAR', 'IAJ',
      'IAU', 'IAUC', 'IAUDS', 'IBVS', 'ICAR', 'ICQ', 'IMO', 'INGTN',
      'IOP', 'ISAS', 'ISSI', 'IUE', 'JAA', 'JAD', 'JAHH', 'JAPA', 'JASS',
      'JAVSO', 'JBAA', 'JENAM', 'JHA', 'JIMO', 'JKAS', 'JPSJ', 'JRASC',
      'JSARA', 'JST', 'KFNT', 'KITP', 'KLUWER', 'KOBV', 'KON', 'LNP',
      'LOC', 'LPI', 'LRR', 'LRSP', 'M&PS', 'M+PS', 'METIC', 'MIT',
      'MNRAS', 'MNSSA', 'MOLDAVIA', 'MPBU', 'MPC', 'MPE', 'MPSA',
      'MmSAI', 'NAS', 'NATURE', 'NCSA', 'NEWA', 'NOAO', 'NRAO', 'NSTED',
      'O+T', 'OAP', 'OBS', 'OEJV', 'OSA', 'PABEI', 'PADEU', 'PAICU',
      'PAICz', 'PAOB', 'PASA', 'PASJ', 'PASP', 'PDS', 'PHIJA', 'PHYS',
      'PJAB', 'PKAS', 'PLR', 'PNAS', 'POBEO', 'PSRD', 'PTP', 'PZP',
      'QJRAS', 'RMXAA', 'RMXAC', 'ROAJ', 'RVMA', 'S&T', 'SABER', 'SAI',
      'SAJ', 'SAO', 'SAS', 'SCI', 'SCIENCE', 'SERB', 'SF2A', 'SLO',
      'SPIE', 'SPIKA', 'SPITZER', 'SPRINGER', 'SPRN', 'STARD', 'STECF',
      'SerAJ', 'T+F', 'TERRAPUB', 'UCP', 'UMI', 'USCI', 'USNO',
      'VATICAN', 'VERSITA', 'WGN', 'WILEY', 'WSPC', 'XMM', 'XTE', 'BLACKWELL',
      'AFOEV', 'ASCL', 'ATNF', 'CJAA', 'CONF', 'EDITOR', 'EGU', 'ELIBRARY', 'IPAP',
      'JDSO', 'LPI', 'MMSAI', 'NCIM', 'PAICZ', 'RSPSA', 'SERAJ', 'SHA', 'SIGMA', 'SUNGE',
      'TELLUS', 'KONKOLY OBSERVATORY',
      'ARPC', 'ANNREV', 'ARMS', 'CSIRO', 'RSC', 'JON', 'JBIS','OUP', 'CSP',
      'DE GRUYTER', 'PASRB', 'BUEOP', 'EAAS', 'AZAJ'],
  0.49: ['PUBLISHER'],
  0.45: ['ARI', 'ARIBIB', 'JSTOR', 'KATKAT',],
  0.4: ['CARL', 'CFA', 'HOLLIS', 'LIBRARY', 'POS', 'PRINCETON', 'SIMBAD', 'CDS',
      'STSCI', 'UTAL',],
  0.375: ['STI', 'WEB',],
  0.35: ['AP', 'CROSSREF', 'GCPD', 'GONG', 'KNUDSEN', 'METBASE',],
  0.3: ['OCR',],
  0.25: ['NED',],
  0.2: ['ARXIV',],
}

__PRIORITIES_JOURNAL = {
  10: ['ADS METADATA',],
  1.0: ['ISI'],
  0.5: ['A&A', 'A&AS', 'A&G', 'AAO', 'AAS', 'AASP', 'AAVSO', 'ACA',
      'ACASN', 'ACHA', 'ACTA', 'ADASS', 'ADIL', 'ADS', 'AFRSK', 'AG',
      'AGDP', 'AGU', 'AIP', 'AJ', 'ALMA', 'AMS', 'AN', 'ANRFM', 'ANRMS',
      'APJ', 'APS', 'ARA&A', 'ARAA', 'ARAC', 'AREPS', 'ARNPS', 'ASBIO',
      'ASD', 'ASL', 'ASP', 'ASPC', 'ASTL', 'ASTRON', 'ATEL', 'ATSIR',
      'AUTHOR', 'OTHER', 'BAAA', 'BAAS', 'BALTA', 'BASBR', 'BASI', 'BAVSR', 'BEO',
      'BESN', 'BLAZ', 'BLGAJ', 'BOTT', 'BSSAS', 'CAPJ', 'CBAT', 'CDC',
      'CEAB', 'CFHT', 'CHAA', 'CHANDRA', 'CHJAA', 'CIEL', 'COAST',
      'COPERNICUS', 'COSKA', 'CSCI', 'CUP', 'CXC', 'CXO', 'DSSN',
      'E&PSL', 'EDP', 'EDP SCIENCES', 'KONKOLY', 'EJTP', 'ELSEVIER', 'ESA', 'ESO', 'ESP', 'EUVE',
      'FCPH', 'FUSE', 'GCN', 'GJI', 'GRG', 'HISSC', 'HST', 'HVAR', 'IAJ',
      'IAU', 'IAUC', 'IAUDS', 'IBVS', 'ICAR', 'ICQ', 'IMO', 'INGTN',
      'IOP', 'ISAS', 'ISSI', 'IUE', 'JAA', 'JAD', 'JAHH', 'JAPA', 'JASS',
      'JAVSO', 'JBAA', 'JENAM', 'JHA', 'JIMO', 'JKAS', 'JPSJ', 'JRASC',
      'JSARA', 'JST', 'KFNT', 'KITP', 'KLUWER', 'KOBV', 'KON', 'LNP',
      'LOC', 'LPI', 'LRR', 'LRSP', 'M&PS', 'M+PS', 'METIC', 'MIT',
      'MNRAS', 'MNSSA', 'MOLDAVIA', 'MPBU', 'MPC', 'MPE', 'MPSA',
      'MmSAI', 'NAS', 'NATURE', 'NCSA', 'NEWA', 'NOAO', 'NRAO', 'NSTED',
      'O+T', 'OAP', 'OBS', 'OEJV', 'OSA', 'PABEI', 'PADEU', 'PAICU',
      'PAICz', 'PAOB', 'PASA', 'PASJ', 'PASP', 'PDS', 'PHIJA', 'PHYS',
      'PJAB', 'PKAS', 'PLR', 'PNAS', 'POBEO', 'PSRD', 'PTP', 'PZP',
      'QJRAS', 'RMXAA', 'RMXAC', 'ROAJ', 'RVMA', 'S&T', 'SABER', 'SAI',
      'SAJ', 'SAO', 'SAS', 'SCI', 'SCIENCE', 'SERB', 'SF2A', 'SLO',
      'SPIE', 'SPIKA', 'SPITZER', 'SPRINGER', 'SPRN', 'STARD', 'STECF',
      'SerAJ', 'T+F', 'TERRAPUB', 'UCP', 'UMI', 'USCI', 'USNO',
      'VATICAN', 'VERSITA', 'WGN', 'WILEY', 'WSPC', 'XMM', 'XTE', 'BLACKWELL',
      'AFOEV', 'ASCL', 'ATNF', 'CJAA', 'CONF', 'EDITOR', 'EGU', 'ELIBRARY', 'IPAP',
      'JDSO', 'LPI', 'MMSAI', 'NCIM', 'PAICZ', 'RSPSA', 'SERAJ', 'SIGMA', 'SUNGE',
      'TELLUS', 'KONKOLY OBSERVATORY',
      'ARPC', 'ANNREV', 'ARMS', 'CSIRO', 'RSC', 'JON', 'JBIS','OUP', 'CSP',
      'DE GRUYTER', 'PASRB', 'BUEOP', 'EAAS', 'AZAJ'],
  0.49: ['PUBLISHER'],
  0.45: ['JSTOR',],
  0.4: ['CARL', 'CFA', 'HOLLIS', 'LIBRARY', 'POS', 'PRINCETON', 'SIMBAD', 'CDS',
      'STSCI', 'UTAL',],
  0.375: ['STI', 'WEB',],
  0.35: ['AP', 'CROSSREF', 'GCPD', 'GONG', 'METBASE',],
  0.3: ['OCR',],
  0.25: ['NED',],
  0.225: ['ARI', 'ARIBIB', 'KNUDSEN', 'KATKAT',],
  0.2: ['ARXIV',],
}

__PRIORITIES_AUTHOR = {
  10: ['ADS METADATA',],
  1.0: ['ISI'],
  0.5: ['A&A', 'A&AS', 'A&G', 'AAO', 'AAS', 'AASP', 'AAVSO', 'ACA',
      'ACASN', 'ACHA', 'ACTA', 'ADASS', 'ADIL', 'ADS', 'AFRSK', 'AG',
      'AGDP', 'AGU', 'AIP', 'AJ', 'ALMA', 'AMS', 'AN', 'ANRFM', 'ANRMS',
      'APJ', 'APS', 'ARA&A', 'ARAA', 'ARAC', 'AREPS', 'ARNPS', 'ASBIO',
      'ASD', 'ASL', 'ASP', 'ASPC', 'ASTL', 'ASTRON', 'ATEL', 'ATSIR',
      'AUTHOR', 'OTHER', 'BAAA', 'BAAS', 'BALTA', 'BASBR', 'BASI', 'BAVSR', 'BEO',
      'BESN', 'BLAZ', 'BLGAJ', 'BOTT', 'BSSAS', 'CAPJ', 'CBAT', 'CDC',
      'CEAB', 'CFHT', 'CHAA', 'CHANDRA', 'CHJAA', 'CIEL', 'COAST',
      'COPERNICUS', 'COSKA', 'CSCI', 'CUP', 'CXC', 'CXO', 'DSSN',
      'E&PSL', 'EDP', 'EDP SCIENCES', 'KONKOLY', 'EJTP', 'ELSEVIER', 'ESA', 'ESO', 'ESP', 'EUVE',
      'FCPH', 'FUSE', 'GCN', 'GJI', 'GRG', 'HISSC', 'HST', 'HVAR', 'IAJ',
      'IAU', 'IAUC', 'IAUDS', 'IBVS', 'ICAR', 'ICQ', 'IMO', 'INGTN',
      'IOP', 'ISAS', 'ISSI', 'IUE', 'JAA', 'JAD', 'JAHH', 'JAPA', 'JASS',
      'JAVSO', 'JBAA', 'JENAM', 'JHA', 'JIMO', 'JKAS', 'JPSJ', 'JRASC',
      'JSARA', 'JST', 'KFNT', 'KITP', 'KLUWER', 'KOBV', 'KON', 'LNP',
      'LOC', 'LPI', 'LRR', 'LRSP', 'M&PS', 'M+PS', 'METIC', 'MIT',
      'MNRAS', 'MNSSA', 'MOLDAVIA', 'MPBU', 'MPC', 'MPE', 'MPSA',
      'MmSAI', 'NAS', 'NATURE', 'NCSA', 'NEWA', 'NOAO', 'NRAO', 'NSTED',
      'O+T', 'OAP', 'OBS', 'OEJV', 'OSA', 'PABEI', 'PADEU', 'PAICU',
      'PAICz', 'PAOB', 'PASA', 'PASJ', 'PASP', 'PDS', 'PHIJA', 'PHYS',
      'PJAB', 'PKAS', 'PLR', 'PNAS', 'POBEO', 'PSRD', 'PTP', 'PZP',
      'QJRAS', 'RMXAA', 'RMXAC', 'ROAJ', 'RVMA', 'S&T', 'SABER', 'SAI',
      'SAJ', 'SAO', 'SAS', 'SCI', 'SCIENCE', 'SERB', 'SF2A', 'SLO',
      'SPIE', 'SPIKA', 'SPITZER', 'SPRINGER', 'SPRN', 'STARD', 'STECF',
      'SerAJ', 'T+F', 'TERRAPUB', 'UCP', 'UMI', 'USCI', 'USNO',
      'VATICAN', 'VERSITA', 'WGN', 'WILEY', 'WSPC', 'XMM', 'XTE', 'BLACKWELL',
      'AFOEV', 'ASCL', 'ATNF', 'CJAA', 'CONF', 'EDITOR', 'EGU', 'ELIBRARY', 'IPAP',
      'JDSO', 'LPI', 'MMSAI', 'NCIM', 'PAICZ', 'RSPSA', 'SERAJ', 'SHA', 'SIGMA', 'SUNGE',
      'TELLUS', 'KONKOLY OBSERVATORY',
      'ARPC', 'ANNREV', 'ARMS', 'CSIRO', 'RSC', 'JON', 'JBIS','OUP', 'CSP',
      'DE GRUYTER', 'PASRB', 'BUEOP', 'EAAS', 'AZAJ'],
  0.49: ['PUBLISHER'],
  0.45: ['ARI', 'ARIBIB', 'JSTOR', 'KATKAT',],
  0.4: ['CARL', 'CFA', 'HOLLIS', 'LIBRARY', 'POS', 'PRINCETON', 'SIMBAD', 'CDS',
      'STSCI', 'UTAL',],
  0.375: ['WEB',],
  0.35: ['AP', 'CROSSREF', 'GCPD', 'GONG', 'KNUDSEN', 'METBASE',],
  0.3: ['OCR',],
  0.25: ['NED',],
  0.225: ['STI',],
  0.2: ['ARXIV',],
}

__PRIORITIES_ABSTRACT = {
  10: ['ADS METADATA',],
  1.0: ['ISI'],
  0.5: ['A&A', 'A&AS', 'A&G', 'AAO', 'AAS', 'AASP', 'AAVSO', 'ACA',
      'ACASN', 'ACHA', 'ACTA', 'ADASS', 'ADIL', 'ADS', 'AFRSK', 'AG',
      'AGDP', 'AGU', 'AIP', 'AJ', 'ALMA', 'AMS', 'AN', 'ANRFM', 'ANRMS',
      'APJ', 'APS', 'ARA&A', 'ARAA', 'ARAC', 'AREPS', 'ARNPS', 'ASBIO',
      'ASD', 'ASL', 'ASP', 'ASPC', 'ASTL', 'ASTRON', 'ATEL', 'ATSIR',
      'AUTHOR', 'OTHER', 'BAAA', 'BAAS', 'BALTA', 'BASBR', 'BASI', 'BAVSR', 'BEO',
      'BESN', 'BLAZ', 'BLGAJ', 'BOTT', 'BSSAS', 'CAPJ', 'CBAT', 'CDC',
      'CEAB', 'CFHT', 'CHAA', 'CHANDRA', 'CHJAA', 'CIEL', 'COAST',
      'COPERNICUS', 'COSKA', 'CSCI', 'CUP', 'CXC', 'CXO', 'DSSN',
      'E&PSL', 'EDP', 'EDP SCIENCES', 'KONKOLY', 'EJTP', 'ELSEVIER', 'ESA', 'ESO', 'ESP', 'EUVE',
      'FCPH', 'FUSE', 'GCN', 'GJI', 'GRG', 'HISSC', 'HST', 'HVAR', 'IAJ',
      'IAU', 'IAUC', 'IAUDS', 'IBVS', 'ICAR', 'ICQ', 'IMO', 'INGTN',
      'IOP', 'ISAS', 'ISSI', 'IUE', 'JAA', 'JAD', 'JAHH', 'JAPA', 'JASS',
      'JAVSO', 'JBAA', 'JENAM', 'JHA', 'JIMO', 'JKAS', 'JPSJ', 'JRASC',
      'JSARA', 'JST', 'KFNT', 'KITP', 'KLUWER', 'KOBV', 'KON', 'LNP',
      'LOC', 'LPI', 'LRR', 'LRSP', 'M&PS', 'M+PS', 'METIC', 'MIT',
      'MNRAS', 'MNSSA', 'MOLDAVIA', 'MPBU', 'MPC', 'MPE', 'MPSA',
      'MmSAI', 'NAS', 'NATURE', 'NCSA', 'NEWA', 'NOAO', 'NRAO', 'NSTED',
      'O+T', 'OAP', 'OBS', 'OEJV', 'OSA', 'PABEI', 'PADEU', 'PAICU',
      'PAICz', 'PAOB', 'PASA', 'PASJ', 'PASP', 'PDS', 'PHIJA', 'PHYS',
      'PJAB', 'PKAS', 'PLR', 'PNAS', 'POBEO', 'PSRD', 'PTP', 'PZP',
      'QJRAS', 'RMXAA', 'RMXAC', 'ROAJ', 'RVMA', 'S&T', 'SABER', 'SAI',
      'SAJ', 'SAO', 'SAS', 'SCI', 'SCIENCE', 'SERB', 'SF2A', 'SLO',
      'SPIE', 'SPIKA', 'SPITZER', 'SPRINGER', 'SPRN', 'STARD', 'STECF',
      'SerAJ', 'T+F', 'TERRAPUB', 'UCP', 'UMI', 'USCI', 'USNO',
      'VATICAN', 'VERSITA', 'WGN', 'WILEY', 'WSPC', 'XMM', 'XTE', 'BLACKWELL',
      'AFOEV', 'ASCL', 'ATNF', 'CJAA', 'CONF', 'EDITOR', 'EGU', 'ELIBRARY', 'IPAP',
      'JDSO', 'LPI', 'MMSAI', 'NCIM', 'PAICZ', 'RSPSA', 'SERAJ', 'SHA', 'SIGMA', 'SUNGE',
      'TELLUS', 'KONKOLY OBSERVATORY',
      'ARPC', 'ANNREV', 'ARMS', 'CSIRO', 'RSC', 'JON', 'JBIS','OUP', 'CSP',
      'DE GRUYTER', 'PASRB', 'BUEOP', 'EAAS', 'AZAJ'],
  0.49: ['PUBLISHER'],
  0.45: ['ARI', 'ARIBIB', 'JSTOR', 'KATKAT',],
  0.4: ['CARL', 'CFA', 'HOLLIS', 'LIBRARY', 'POS', 'PRINCETON', 'SIMBAD', 'CDS',
      'STSCI', 'UTAL',],
  0.375: ['WEB',],
  0.35: ['AP', 'CROSSREF', 'GCPD', 'GONG', 'KNUDSEN', 'METBASE',],
  0.3: ['OCR',],
  0.255:['ARXIV',],
  0.25: ['NED',],
  0.2: ['STI'],
}

__PRIORITIES_REFERENCES = {
  10: ['AUTHOR',],
  9.5: ['ISI',],
  9.1: ['SPRINGER',],
  9.05:['OTHER',],
  9: ['A&A', 'A&AS', 'A&G', 'AAO', 'AAS', 'AASP', 'AAVSO', 'ACA',
      'ACASN', 'ACHA', 'ACTA', 'ADASS', 'ADIL', 'ADS', 'AFRSK', 'AG',
      'AGDP', 'AGU', 'AIP', 'AJ', 'ALMA', 'AMS', 'AN', 'ANRFM', 'ANRMS',
      'APJ', 'APS', 'ARA&A', 'ARAA', 'ARAC', 'AREPS', 'ARNPS', 'ASBIO',
      'ASD', 'ASL', 'ASP', 'ASPC', 'ASTL', 'ASTRON', 'ATEL', 'ATSIR',
      'BAAA', 'BAAS', 'BALTA', 'BASBR', 'BASI', 'BAVSR', 'BEO',
      'BESN', 'BLAZ', 'BLGAJ', 'BOTT', 'BSSAS', 'CAPJ', 'CBAT', 'CDC',
      'CEAB', 'CFHT', 'CHAA', 'CHANDRA', 'CHJAA', 'CIEL', 'COAST',
      'COPERNICUS', 'COSKA', 'CSCI', 'CUP', 'CXC', 'CXO', 'DSSN',
      'E&PSL', 'EDP', 'EDP SCIENCES', 'KONKOLY', 'EJTP', 'ELSEVIER', 'ESA', 'ESO', 'ESP', 'EUVE',
      'FCPH', 'FUSE', 'GCN', 'GJI', 'GRG', 'HISSC', 'HST', 'HVAR', 'IAJ',
      'IAU', 'IAUC', 'IAUDS', 'IBVS', 'ICAR', 'ICQ', 'IMO', 'INGTN',
      'IOP', 'ISAS', 'ISSI', 'IUE', 'JAA', 'JAD', 'JAHH', 'JAPA', 'JASS',
      'JAVSO', 'JBAA', 'JENAM', 'JHA', 'JIMO', 'JKAS', 'JPSJ', 'JRASC',
      'JSARA', 'JST', 'KFNT', 'KITP', 'KLUWER', 'KOBV', 'KON', 'LNP',
      'LOC', 'LPI', 'LRR', 'LRSP', 'M&PS', 'M+PS', 'METIC', 'MIT',
      'MNRAS', 'MNSSA', 'MOLDAVIA', 'MPBU', 'MPC', 'MPE', 'MPSA',
      'MmSAI', 'NAS', 'NATURE', 'NCSA', 'NEWA', 'NOAO', 'NRAO', 'NSTED',
      'O+T', 'OAP', 'OBS', 'OEJV', 'OSA', 'PABEI', 'PADEU', 'PAICU',
      'PAICz', 'PAOB', 'PASA', 'PASJ', 'PASP', 'PDS', 'PHIJA', 'PHYS',
      'PJAB', 'PKAS', 'PLR', 'PNAS', 'POBEO', 'PSRD', 'PTP', 'PZP',
      'QJRAS', 'RMXAA', 'RMXAC', 'ROAJ', 'RVMA', 'S&T', 'SABER', 'SAI',
      'SAJ', 'SAO', 'SAS', 'SCI', 'SCIENCE', 'SERB', 'SF2A', 'SLO',
      'SPIE', 'SPIKA', 'SPITZER', 'SPRN', 'STARD', 'STECF',
      'STSCI', 'SerAJ', 'T+F', 'TERRAPUB', 'UCP', 'UMI', 'USCI', 'USNO',
      'VATICAN', 'VERSITA', 'WGN', 'WILEY', 'WSPC', 'XMM', 'XTE',
      'ARI', 'KATKAT', 'ARIBIB', 'JSTOR', 'CARL', 'CFA', 'HOLLIS', 'LIBRARY',
      'POS', 'PRINCETON', 'SIMBAD', 'CDS','UTAL', 'STI', 'WEB',
      'AP', 'GCPD', 'GONG', 'KNUDSEN', 'METBASE', 'NED', 'BLACKWELL',
      'AFOEV', 'ASCL', 'ATNF', 'CJAA', 'CONF', 'EDITOR', 'EGU', 'ELIBRARY', 'IPAP',
      'JDSO', 'LPI', 'MMSAI', 'NCIM', 'PAICZ', 'RSPSA', 'SERAJ', 'SHA', 'SIGMA', 'SUNGE',
      'TELLUS', 'KONKOLY OBSERVATORY',
      'ARPC', 'ANNREV', 'ARMS', 'CSIRO', 'RSC', 'JON', 'JBIS','OUP', 'CSP',
      'DE GRUYTER', 'PASRB', 'BUEOP', 'EAAS', 'AZAJ'],
  8.9: ['PUBLISHER'],
  8.5: ['OCR', 'ADS METADATA'],
  8: ['CROSSREF',],
  5: ['ARXIV',],
}

PRIORITIES = {
  'default': dict((source, score)
    for score, sources in __PRIORITIES_DEFAULT.iteritems()
    for source in sources),
  'journal': dict((source, score)
    for score, sources in __PRIORITIES_JOURNAL.iteritems()
    for source in sources),
  'canonical_journal': dict((source, score)
    for score, sources in __PRIORITIES_JOURNAL.iteritems()
    for source in sources),
  'author': dict((source, score)
    for score, sources in __PRIORITIES_AUTHOR.iteritems()
    for source in sources),
  'reference': dict((source, score)
    for score, sources in __PRIORITIES_REFERENCES.iteritems()
    for source in sources),
  'abstract': dict((source, score)
    for score, sources in __PRIORITIES_ABSTRACT.iteritems()
    for source in sources),
}



#References with these origins will always be added to merged reference metadata blocks.
REFERENCES_ALWAYS_APPEND = ['ISI', 'AUTHOR', 'OTHER', 'CROSSREF']