name: GitHub Actions CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: install python2
      run: |
        sudo apt-get update
        sudo apt-get install python2.7 -y
        sudo apt-get install python2.7-dev -y
        sudo update-alternatives --install /usr/bin/python python /usr/bin/python2.7 1

        venv_base_path="/tmp/python27/venv"
        venv_dir="bin"

        echo "Bootstrapping pip"

        curl https://bootstrap.pypa.io/pip/2.7/get-pip.py --output get-pip.py
        python get-pip.py
        rm -f get-pip.py

        echo "Installing virtualenv"
        python -m pip install virtualenv

        python -m virtualenv ${venv_base_path}

        source ${venv_base_path}/${venv_dir}/activate

        python -m pip --no-python-version-warning --disable-pip-version-check install --upgrade pip setuptools

        echo "${venv_base_path}/${venv_dir}" >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        python -m pip install --upgrade setuptools pip
        pip install -U -r requirements.txt
        pip install -U -r dev-requirements.txt

    - name: Test with pytest
      run: |
        py.test

    - uses: actions/upload-artifact@v4
      with:
        name: coverage-import
        path: .coverage


  coveralls:

    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade wheel setuptools pip
        pip install coverage==5.2.1
        pip install coveralls==2.2.0

    - uses: actions/download-artifact@master
      with:
        name: coverage-import

    - name: Coveralls
      run: coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
